-- Integration checks. Creates disposable auth identities inside one rolled-back transaction.
-- Run as postgres in the SQL editor / Supabase MCP. No test users or saved games remain.
begin;
create temporary table sim_test_context(user_a uuid,user_b uuid,run_id uuid);
insert into sim_test_context values(gen_random_uuid(),gen_random_uuid(),null);
insert into auth.users(id) select user_a from sim_test_context union all select user_b from sim_test_context;
grant select,update on sim_test_context to authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',user_a,'role','authenticated')::text,true) from sim_test_context;
set local role authenticated;
do $$
declare r uuid; s uuid; n integer; failed boolean; choices jsonb;
begin
 select id into s from public.sim_scenarios where city_id='madrid' and code='base' and version_id='alpha-1';
 r:=public.sim_create_run(s,5,'Prueba transaccional','Explorar');
 update sim_test_context set run_id=r;
 if (select count(*) from public.sim_turn_groups where run_id=r and turn_no=0)<>6 then raise exception 'FAIL six groups'; end if;
 if (select sum(weight_percent) from public.sim_turn_groups where run_id=r and turn_no=0)<>100 then raise exception 'FAIL weights'; end if;
 if not exists(select 1 from public.sim_turns where run_id=r and turn_no=0 and rent_home=rent_m2*reference_area_m2 and sale_home=sale_m2*reference_area_m2) then raise exception 'FAIL home prices'; end if;
 failed:=false;
 begin perform public.sim_create_run(s,6,'Duración inválida','Explorar'); exception when others then failed:=true; end;
 if not failed then raise exception 'FAIL duration'; end if;
 failed:=false;
 begin update public.sim_runs set current_turn=10 where id=r; exception when insufficient_privilege then failed:=true; end;
 if not failed then raise exception 'FAIL direct writes'; end if;
 failed:=false;
 begin perform public.sim_advance_turn(r,0,'[{"measure_id":"public_housing"}]'); exception when others then failed:=true; end;
 if not failed or (select current_turn from public.sim_runs where id=r)<>0 or (select count(*) from public.sim_turns where run_id=r)<>1 then raise exception 'FAIL rollback unfunded'; end if;
 failed:=false;
 begin perform public.sim_advance_turn(r,0,'[{},{},{},{},{},{}]'); exception when others then failed:=true; end;
 if not failed then raise exception 'FAIL five limit'; end if;
 choices:='[{"measure_id":"public_housing","intensity":1,"funding":[{"source_id":"transport","initial_amount":1000,"quarterly_amount":200}]}]';
 n:=public.sim_advance_turn(r,0,choices);
 if n<>1 then raise exception 'FAIL advance'; end if;
 if not exists(select 1 from public.sim_turn_budgets where run_id=r and turn_no=1 and source_id='transport' and committed=1200 and remaining=8800) then raise exception 'FAIL finance'; end if;
 failed:=false;
 begin perform public.sim_advance_turn(r,0,'[]'); exception when serialization_failure then failed:=true; end;
 if not failed then raise exception 'FAIL stale turn'; end if;
 failed:=false;
 begin perform public.sim_advance_turn(r,1,choices); exception when others then failed:=true; end;
 if not failed then raise exception 'FAIL already active'; end if;
 n:=public.sim_advance_turn(r,1,'[]');
 if not exists(select 1 from public.sim_turn_budgets where run_id=r and turn_no=2 and source_id='transport' and committed=200) then raise exception 'FAIL recurring reservation'; end if;
 for i in 2..19 loop perform public.sim_advance_turn(r,i,'[]'); end loop;
 if not exists(select 1 from public.sim_runs where id=r and status='completed' and current_turn=20) then raise exception 'FAIL completion'; end if;
 if (select count(*) from public.sim_turns where run_id=r)<>21 then raise exception 'FAIL history'; end if;
 failed:=false;
 begin perform public.sim_advance_turn(r,20,'[]'); exception when others then failed:=true; end;
 if not failed then raise exception 'FAIL completed game'; end if;
end $$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',user_b,'role','authenticated')::text,true) from sim_test_context;
set local role authenticated;
do $$ declare r uuid; failed boolean:=false; begin
 select run_id into r from sim_test_context;
 if exists(select 1 from public.sim_runs where id=r) or exists(select 1 from public.sim_turns where run_id=r) or exists(select 1 from public.sim_funding where run_id=r) then raise exception 'FAIL cross-user visibility'; end if;
 begin perform public.sim_advance_turn(r,20,'[]'); exception when insufficient_privilege then failed:=true; end;
 if not failed then raise exception 'FAIL cross-user mutation'; end if;
end $$;
reset role;
set local role anon;
do $$ declare failed boolean:=false; begin
 if (select count(*) from public.sim_cities)<>5 then raise exception 'FAIL public catalogue'; end if;
 begin perform public.sim_create_run(null,5,'Anon','Explorar'); exception when insufficient_privilege then failed:=true; end;
 if not failed then raise exception 'FAIL anonymous create'; end if;
 failed:=false;
 begin perform count(*) from public.sim_runs; exception when insufficient_privilege then failed:=true; end;
 if not failed then raise exception 'FAIL anonymous saves'; end if;
end $$;
reset role;
rollback;
select 'PASS: create, pricing, six groups, duration, RLS, funding, rollback, recurring commitments, five-limit, stale turn, history and completion' as integration_checks;
