-- Integration checks for funded, modulated policies. Everything rolls back.
begin;
create temporary table sim_a2_context(user_a uuid,run_id uuid);
insert into sim_a2_context values(gen_random_uuid(),null);
insert into auth.users(id) select user_a from sim_a2_context;
grant select,update on sim_a2_context to authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',user_a,'role','authenticated')::text,true) from sim_a2_context;
set local role authenticated;
do $$
declare r uuid;s uuid;failed boolean;baseline numeric;regulated numeric;tenant_unrest numeric;
begin
 if (select count(*) from public.sim_measures where version_id='alpha-2')<>50 then raise exception 'FAIL catalogue';end if;
 if (select count(*) from public.sim_sources)<>25 then raise exception 'FAIL references';end if;
 select id into s from public.sim_scenarios where city_id='madrid' and code='base' and version_id='alpha-2';
 if (select count(*) from public.sim_scenario_budgets where scenario_id=s)<>17 then raise exception 'FAIL financing choices';end if;
 r:=public.sim_create_run(s,5,'Alpha 2 transaccional','Explorar');update sim_a2_context set run_id=r;
 failed:=false;
 begin perform public.sim_advance_turn(r,0,'[{"measure_id":"a2_freeze","intensity":0.5,"funding":[]}]');exception when others then failed:=true;end;
 if not failed or (select current_turn from public.sim_runs where id=r)<>0 then raise exception 'FAIL unfunded rollback';end if;
 failed:=false;
 begin perform public.sim_advance_turn(r,0,'[{"measure_id":"a2_freeze","intensity":0.5,"funding":[{"source_id":"a2_tax_irpf","initial_amount":400000,"quarterly_amount":150000}]},{"measure_id":"a2_index_cap","intensity":0.5,"funding":[{"source_id":"a2_tax_irpf","initial_amount":300000,"quarterly_amount":90000}]}]');exception when others then failed:=true;end;
 if not failed or exists(select 1 from public.sim_decisions where run_id=r) then raise exception 'FAIL exclusivity rollback';end if;
 failed:=false;
 begin perform public.sim_advance_turn(r,0,'[{"measure_id":"a2_freeze","funding":[{"source_id":"a2_tax_nonresident","initial_amount":800000,"quarterly_amount":300000}]}]');exception when others then failed:=true;end;
 if not failed then raise exception 'FAIL source capacity';end if;
 perform public.sim_advance_turn(r,0,'[{"measure_id":"a2_freeze","intensity":0.5,"funding":[{"source_id":"a2_tax_irpf","initial_amount":400000,"quarterly_amount":150000}]}]');
 select rent_m2 into regulated from public.sim_turns where run_id=r and turn_no=1;
 baseline:=18*1.001;
 if regulated>=baseline or (select (state->>'free_rent_m2')::numeric from public.sim_turns where run_id=r and turn_no=1)<=baseline then raise exception 'FAIL covered versus free market';end if;
 select unrest into tenant_unrest from public.sim_turn_groups where run_id=r and turn_no=1 and group_id='tenants';
 if tenant_unrest>=75 then raise exception 'FAIL modulated happiness';end if;
 if not exists(select 1 from public.sim_turn_budgets where run_id=r and turn_no=1 and source_id='a2_tax_irpf' and committed=550000) then raise exception 'FAIL funding incidence';end if;
 perform public.sim_advance_turn(r,1,'[{"measure_id":"a2_public_build","intensity":0.5,"funding":[{"source_id":"a2_cut_pensions","initial_amount":30000000,"quarterly_amount":7500000}]}]');
 if not exists(select 1 from public.sim_decisions where run_id=r and measure_id='a2_public_build' and initial_cost=30000000 and post_quarterly_cost=250000) then raise exception 'FAIL realistic scaled costs';end if;
 for t in 2..7 loop perform public.sim_advance_turn(r,t,'[]');end loop;
 -- After eight quarters the rent control expires; construction has not completed yet.
 perform public.sim_advance_turn(r,8,'[]');
 if (select rent_m2 from public.sim_turns where run_id=r and turn_no=9)<>round(18*1.009,2) then raise exception 'FAIL expiration / construction delay';end if;
 if exists(select 1 from public.sim_turn_budgets where run_id=r and turn_no=9 and source_id='a2_tax_irpf' and committed<>0) then raise exception 'FAIL transfer expiry';end if;
 for t in 9..12 loop perform public.sim_advance_turn(r,t,'[]');end loop;
 if not exists(select 1 from public.sim_turn_budgets where run_id=r and turn_no=13 and source_id='a2_cut_pensions' and committed=7500000) then raise exception 'FAIL last construction payment';end if;
 perform public.sim_advance_turn(r,13,'[]');
 if not exists(select 1 from public.sim_turn_budgets where run_id=r and turn_no=14 and source_id='a2_cut_pensions' and committed=250000) then raise exception 'FAIL ongoing maintenance';end if;
 if (select rent_m2 from public.sim_turns where run_id=r and turn_no=14)>=round(18*1.014,2) then raise exception 'FAIL persistent completed homes';end if;
 for t in 14..19 loop perform public.sim_advance_turn(r,t,'[]');end loop;
 if not exists(select 1 from public.sim_runs where id=r and status='completed') then raise exception 'FAIL completion';end if;
 if exists(select 1 from public.sim_turn_groups where run_id=r and (unrest<0 or unrest>100)) then raise exception 'FAIL bounded happiness';end if;
 if exists(select 1 from public.sim_turns where run_id=r and (rent_m2<=0 or sale_m2<=0)) then raise exception 'FAIL price floor';end if;
end $$;
reset role;
rollback;
