"""Build auditable local catalogue. All effect coefficients are game assumptions."""
from pathlib import Path
import json
sources={
'civio':{'title':'Civio · visualización del proyecto PGE 2023','url':'https://civio.es/novedades/2022/10/10/visualizacion-proyecto-de-presupuestos-de-2023-pge/','kind':'budget_navigation'},
'pge_spending':{'title':'Hacienda · PGE 2023 aprobado, políticas de gasto, capítulos 1–9','url':'https://www.sepg.pap.hacienda.gob.es/Presup/PGE2023Ley/MaestroDocumentos/PGE-ROM/doc/HTM/N_23_E_R_6_2_R_3_1.HTM','kind':'historical_budget'},
'pge_tax':{'title':'Hacienda · ingresos PGE 2023, antes de cesiones territoriales','url':'https://www.sepg.pap.hacienda.gob.es/Presup/PGE2023Proyecto/MaestroDocumentos/PGE-ROM/doc/3/1/3/2/N_23_A_A_1_3_2_3.PDF','kind':'historical_tax_reference'},
'bde':{'title':'Banco de España · Informe Anual 2023, capítulo 4','url':'https://www.bde.es/f/webbe/SES/Secciones/Publicaciones/PublicacionesAnuales/InformesAnuales/23/Fich/InfAnual_2023_Cap4.pdf','kind':'diagnosis'},
'bde_rent':{'title':'Banco de España · mercado del alquiler, documento ocasional 2432','url':'https://www.bde.es/wbe/en/publicaciones/analisis-economico-investigacion/documentos-ocasionales/el-mercado-del-alquiler-de-vivienda-residencial-en-espana-evolucion-reciente-determinantes-e-indicadores-de-esfuerzo.html','kind':'diagnosis'},
'oecd_actions':{'title':'OCDE · Housing policy action','url':'https://www.oecd.org/en/data/tools/housing-policy-action.html','kind':'policy_framework'},
'oecd_tax':{'title':'OCDE · Housing Taxation in OECD Countries','url':'https://www.oecd.org/en/publications/housing-taxation-in-oecd-countries_03dfe007-en.html','kind':'tax_framework'},
'oecd_reform':{'title':'OCDE · An Agenda for Housing Policy Reform, 2024','url':'https://www.oecd.org/content/dam/oecd/en/publications/reports/2024/10/an-agenda-for-housing-policy-reform_450b3a9a/ddb57031-en.pdf','kind':'policy_framework'},
'sf_rent':{'title':'Diamond, McQuade y Qian · rent control, San Francisco','url':'https://www.nber.org/papers/w24181','kind':'causal_study_other_market'},
'berlin':{'title':'CESifo · Berlin rent cap, Working Paper 10493','url':'https://www.ifo.de/DocDL/cesifo1_wp10493.pdf','kind':'study_other_market'},
'eu_rent':{'title':'Comisión Europea · Housing in the EU, discussion paper 228','url':'https://economy-finance.ec.europa.eu/document/download/11912749-99e7-4ade-be0c-890a6d6d55ee_en?filename=dp228_en.pdf','kind':'comparative_policy'},
'lau':{'title':'BOE · Ley de Arrendamientos Urbanos, texto consolidado','url':'https://www.boe.es/buscar/act.php?id=BOE-A-1994-26003','kind':'legal_reference'},
'law_housing':{'title':'BOE · Ley 12/2023, vivienda','url':'https://www.boe.es/buscar/pdf/2023/BOE-A-2023-12203-consolidado.pdf','kind':'legal_reference'},
'plan2026':{'title':'BOE · Plan Estatal de Vivienda 2026–2030, RD 326/2026','url':'https://www.boe.es/eli/es/rd/2026/04/22/326/con','kind':'aid_limits_not_total_cost'},
'rehab':{'title':'BOE · rehabilitación, RD 853/2021','url':'https://www.boe.es/buscar/act.php?id=BOE-A-2021-16233','kind':'aid_limits_not_total_cost'},
'vallecas':{'title':'Ayuntamiento de Madrid · Vallecas 62, 100 viviendas, inversión 13,6 M€','url':'https://www.madrid.es/portales/munimadrid/es/Inicio/El-Ayuntamiento/Moratalaz/El-Ayuntamiento-comienza-las-obras-de-100-nuevas-viviendas-para-alquiler-asequible-en-Villa-de-Vallecas/?vgnextchannel=7cb0ca5d5fb96010VgnVCM100000dc0ca8c0RCRD&vgnextfmt=default&vgnextoid=02a272e2ad2fc810VgnVCM1000001d4a900aRCRD','kind':'project_2023_announced_2024'},
'canaveral':{'title':'Ayuntamiento de Madrid · 1.212 viviendas, inversión 190 M€','url':'https://diario.madrid.es/blog/notas-de-prensa/comienzan-las-obras-de-la-ultima-promocion-del-ayuntamiento-en-el-canaveral/','kind':'programme_investment_2023'},
'ico':{'title':'ICO · Plan de Actuación 2025, avales de primera vivienda','url':'https://www.ico.es/documents/20124/39532/20250620_Plan%2Bde%2BActuacio%CC%81n_25_ICO_VF.pdf/e03358d8-7468-2ccc-a552-3555c409776d?t=1750666924689','kind':'guarantee_not_cash_cost'},
'str':{'title':'Comisión Europea · transparencia alquileres cortos, aplicación mayo 2026','url':'https://single-market-economy.ec.europa.eu/news/new-rules-bring-increased-transparency-short-term-rentals-sector-2026-05-20_en','kind':'current_regulation'},
'capital':{'title':'EUR-Lex · libre circulación de capitales','url':'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=LEGISSUM%3Afree_movement_of_capital','kind':'legal_constraint'},
'eu_proposal':{'title':'EUR-Lex · propuesta COM(2026)599; no equivale a ley aprobada','url':'https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=celex%3A52026PC0599','kind':'proposal_not_law'},
'jrc':{'title':'JRC · Housing First y sinhogarismo','url':'https://publications.jrc.ec.europa.eu/repository/handle/JRC136178','kind':'policy_brief'},
'democracy':{'title':'Positech · Democracy 3, sliders y efectos por colectivos','url':'https://positech.co.uk/democracy3/','kind':'game_design'},
'democracy_mod':{'title':'Positech · guía oficial de modding Democracy 3','url':'https://www.positech.co.uk/democracy3/modding.html','kind':'game_design'},
'democracy_private':{'title':'Cliff Harris · Democracy 3, sector privado, enero 2013','url':'https://www.positech.co.uk/cliffsblog/2013/01/','kind':'developer_diary'}
}
categories={'controls':'Control de precios','admin':'Simplificación administrativa','supply':'Construcción y suelo','mobilise':'Vivienda existente','access':'Acceso y protección','tax':'Fiscalidad de vivienda','demand':'Turismo y demanda','territory':'Territorio y movilidad'}
# id|category|name|full application|initial euros|quarterly euros|duration quarters|delay|rent %|sale %|free rent %|six happiness points|mechanism|benefit|risk|sources
raw='''
freeze|controls|Congelación temporal de alquileres|100 % del parque elegible|800000|300000|8|0|-5|-2|4|-9,-8,9,2,1,0|Congelar rentas vigentes protege contratos cubiertos; puede reducir nuevas ofertas|Estabilidad inmediata de quienes tienen contrato|Retirada de oferta y selección de inquilinos|sf_rent,berlin,lau
index_cap|controls|Límite de actualización anual|100 % de contratos elegibles|600000|180000|20|0|-2|-1|1|-4,-3,5,1,0,0|Limitar subidas dentro del contrato amortigua inflación sin fijar todo el precio inicial|Menor incertidumbre del inquilino|Prima de entrada y menor rentabilidad real|eu_rent,lau
benchmark|controls|Tope por índice de referencia|100 % de zonas elegibles|1200000|350000|20|1|-4|-2|2|-7,-6,7,2,1,0|Topar nuevos contratos según una referencia segmentada exige datos y fiscalización|Contener nuevos alquileres regulados|Evasión a temporada y errores de referencia|law_housing,bde_rent
income_cap|controls|Alquiler ligado a ingresos del hogar|100 % de hogares elegibles|1500000|450000|20|1|-6|-2|5|-10,-9,10,1,0,0|Vincular renta al ingreso protege hogares pero traslada al arrendador el riesgo de ingresos|Menor esfuerzo de hogares cubiertos|Selección por renta y escasez para nuevos demandantes|oecd_reform,eu_rent
cost_return|controls|Alquiler por costes y amortización|100 % del parque elegible|2000000|500000|20|2|-3|-1|2|-5,-5,6,1,0,0|Reconocer costes, mejoras y retorno cambia la renta de referencia; requiere auditar activos|Premiar mejora real y limitar excesos|Costes de valoración y posible salida de oferta|oecd_actions
voluntary_cap|controls|Convenios voluntarios de alquiler asequible|1000 viviendas conveniadas|500000|750000|20|1|-2|0|-1|3,2,6,1,0,0|Compensar una rebaja voluntaria mantiene incentivos y exige gasto fiscal o transferencias|Rentas menores con adhesión del propietario|Coste público y adhesión limitada|law_housing,plan2026
protected_sale|controls|Precio máximo de venta protegida|100 % del parque protegido elegible|600000|160000|40|1|0|-1|0|-2,-3,2,5,1,0|Reservar precio y recompra en vivienda protegida mantiene asequibilidad de ese parque|Evitar privatización de la ayuda inicial|Restricción de reventa y administración|law_housing,plan2026
admin_digital|admin|Nivel 1 · ventanilla única digital|100 % de expedientes elegibles|3000000|250000|20|2|-1|-1|-1|2,3,2,2,1,1|Un expediente compartido reduce duplicidades conservando controles técnicos|Menos trámites repetidos|Coste de implantación y transición|oecd_reform,bde
admin_parallel|admin|Nivel 2 · informes en paralelo|100 % de expedientes elegibles|2000000|350000|20|2|-2|-2|-2|3,4,3,3,2,1|Coordinar informes y plazos evita esperas secuenciales sin eliminar garantías|Mayor previsibilidad de licencias|Requiere coordinación y personal|oecd_reform,bde
admin_standard|admin|Nivel 3 · proyectos homologados|100 % de expedientes elegibles|4000000|450000|20|3|-3|-3|-3|3,5,4,4,2,1|Homologar tipologías y códigos repetibles acelera revisión con inspección final|Menor coste técnico repetido|Menos adaptación a casos singulares|oecd_reform,plan2026
admin_risk|admin|Nivel 4 · declaración responsable por riesgo|100 % de actuaciones de bajo riesgo|2500000|700000|20|2|-3|-3|-3|4,5,3,4,2,-1|Sustituir autorización previa solo en bajo riesgo exige inspección posterior suficiente|Ejecución más rápida en casos aptos|Fallos de inspección y litigios|oecd_reform,bde
admin_staff|admin|Refuerzo de técnicos e inspectores|100 nuevos puestos|0|1750000|20|1|-1|-1|-1|2,3,2,2,1,2|Contratar técnicos reduce colas e incrementa capacidad de control|Plazos y cumplimiento mejores|Coste recurrente de plantilla|oecd_reform
public_build|supply|Construcción pública directa|1000 viviendas nuevas|60000000|15000000|12|12|-4|-2|-4|-2,-2,7,4,2,1|Añadir alquiler público amplía oferta después de suelo, obra y adjudicación|Parque asequible duradero|Coste, retrasos y presión sobre capacidad constructiva|vallecas,canaveral,plan2026
ppp_build|supply|Suelo público con concesión asequible|1000 viviendas nuevas|10000000|4000000|12|12|-3|-2|-3|0,5,5,3,1,1|Ceder suelo y pactar rentas moviliza capital privado con obligaciones y riesgo contractual|Menor desembolso directo de obra|Suelo cedido y rentabilidad privada no son gratuitos|plan2026,bde
cooperative|supply|Cooperativas en cesión de uso|500 viviendas|10000000|2500000|12|12|-2|-1|-2|0,1,5,3,1,2|Cesión de suelo y préstamos facilitan una tenencia colectiva estable|Alternativa al alquiler y compra convencionales|Gestión colectiva y acceso a financiación|oecd_reform,plan2026
land_ready|supply|Urbanizar suelo con infraestructuras|1000 viviendas potenciales|10000000|2000000|12|8|-2|-3|-2|2,5,3,4,2,0|Convertir suelo en solares requiere redes y servicios antes de construir|Oferta futura viable|Impacto ambiental y costes de urbanización|bde,oecd_reform
upzone|supply|Densificar cerca de transporte|100 % de áreas aptas|3000000|300000|20|8|-3|-4|-3|1,5,4,5,2,-2|Permitir más viviendas por solar eleva capacidad; depende de promoción e infraestructura|Aprovechar zonas conectadas|Obras, congestión y oposición vecinal|oecd_reform,bde
infill|supply|Rellenar vacíos y reconvertir usos|1000 viviendas potenciales|3000000|600000|12|6|-2|-2|-2|2,4,3,4,2,0|Habilitar solares y edificios aptos aprovecha ciudad consolidada|Menor expansión territorial|No todo local u oficina es habitable|oecd_actions,bde
industrial|supply|Incentivar construcción industrializada|1000 viviendas de proyectos existentes|5000000|1000000|12|6|-1|-2|-1|2,4,3,3,1,1|Estandarizar fabricación reduce tiempos cuando hay volumen y logística|Más capacidad y plazos previsibles|Inversión inicial y dependencia de proveedores|plan2026
training|supply|Formación en oficios de construcción|2000 plazas de formación|3000000|1500000|12|8|-1|-1|-1|1,3,2,2,1,2|Aumentar mano de obra especializada reduce cuellos de botella gradualmente|Capacidad de producción y empleo|Resultados lentos y gasto formativo|bde,oecd_reform
building_code|supply|Revisar exigencias constructivas no esenciales|100 % de requisitos revisables|2000000|200000|20|6|-2|-2|-2|3,4,2,3,2,-2|Simplificar exigencias redundantes reduce costes manteniendo seguridad y accesibilidad|Menor coste de promoción|Riesgo de perder calidad si se aplica mal|oecd_reform
rural_land|supply|Habilitar crecimiento en suelo no urbano apto|1000 viviendas potenciales|12000000|2500000|16|12|-1|-2|-1|2,4,2,3,2,-3|Ampliar suelo técnicamente apto requiere servicios y excluye zonas protegidas o de riesgo|Nueva capacidad territorial|Dispersión, transporte y límites ambientales|oecd_reform,bde
buy_existing|mobilise|Comprar viviendas para alquiler público|500 viviendas|142800000|250000|40|2|-1|1|-1|2,1,5,-1,-1,1|Comprar cambia tenencia y acceso pero no añade vivienda física|Parque social más rápido|Demanda pública puede elevar precios de compra|plan2026,bde
empty_rehab|mobilise|Rehabilitar vivienda vacía habitable|1000 viviendas|20000000|250000|8|4|-2|-1|-2|4,2,5,2,1,1|Financiar reparación a cambio de alquiler habitual moviliza parque utilizable|Aprovechar vivienda existente|Vacíos mal ubicados y verificación|plan2026,bde
energy_rehab|mobilise|Rehabilitación energética|1000 viviendas|11600000|200000|8|4|0|1|0|5,3,4,1,1,5|Mejorar eficiencia reduce facturas pero no implica nueva oferta|Menor gasto energético y calidad|Capitalización de mejoras en rentas y venta|rehab,plan2026
accessibility|mobilise|Adaptar viviendas y ascensores|1000 viviendas|13000000|200000|8|4|0|0|0|4,1,4,1,0,7|Accesibilidad mejora uso y autonomía sin bajar necesariamente precios|Mejor habitabilidad para mayores y discapacidad|Coste de obra y copago|plan2026
rental_guarantee|mobilise|Seguro público de impago|5000 contratos|500000|750000|20|1|-1|0|-1|6,3,3,1,0,1|Cubrir parte del riesgo incentiva arrendar con condiciones de acceso|Mayor seguridad y oferta|Riesgo moral y siniestros del seguro|plan2026,oecd_reform
mediation|mobilise|Intermediación y garantías de alquiler|5000 contratos|500000|500000|20|1|-1|0|-1|4,2,3,1,0,1|Asesorar y mediar reduce costes de contratación y conflicto|Confianza entre partes|Efecto limitado sin viviendas disponibles|plan2026
sareb|mobilise|Movilizar inmuebles públicos y SAREB aptos|500 viviendas|20000000|250000|12|4|-1|0|-1|0,0,4,2,1,1|Adecuar activos aptos exige comprobar ubicación, ocupación y propiedad|Aprovechar activos existentes|Muchos activos requieren inversión o no encajan con demanda|plan2026,bde
rent_aid_target|access|Ayuda al alquiler focalizada|5000 hogares · 250 €/mes|500000|3750000|8|0|1|0|1|2,1,8,-1,0,0|Una transferencia reduce esfuerzo neto de beneficiarios pero eleva demanda con oferta rígida|Alivio económico inmediato|Parte puede capitalizarse en alquiler|plan2026,oecd_tax
rent_aid_universal|access|Ayuda amplia al alquiler|10000 hogares · 250 €/mes|1000000|7500000|8|0|2|1|2|3,2,7,-2,-1,0|Extender ayudas aumenta demanda y coste más que focalizarlas|Cobertura amplia|Mayor capitalización y gasto recurrente|oecd_reform,oecd_tax
housing_first|access|Housing First y apoyo residencial|500 hogares|1000000|2250000|20|1|0|0|0|1,0,4,0,0,2|Vivienda estable con apoyo aborda sinhogarismo; el efecto en precio medio es pequeño|Estabilidad de hogares vulnerables|Servicios intensivos y disponibilidad de viviendas|jrc,plan2026
legal_aid|access|Asistencia jurídica y prevención de desahucios|5000 hogares|300000|1000000|20|0|0|0|0|-1,0,5,0,0,1|Asistencia y mediación reducen expulsión evitable sin crear oferta|Protección y resolución de conflictos|Coste y posible alargamiento de procesos|plan2026,oecd_reform
mortgage_guarantee|access|Aval parcial para primera vivienda|2000 hipotecas · aval 20 %|5000000|200000|20|0|0|2|0|2,3,1,7,0,0|Aval permite comprar con menos ahorro, pero no es subvención por todo el principal|Acceso de hogares solventes sin entrada|Pasivo contingente y presión de compra|ico,oecd_tax
mortgage_relief|access|Deducción fiscal de intereses hipotecarios|5000 hogares · 1500 €/año|250000|1875000|20|0|0|2|0|2,2,-1,6,0,2|Subvencionar intereses eleva capacidad de pago y puede capitalizarse en precios|Menor coste neto de financiación|Sesgo a propiedad y pérdida de recaudación|oecd_tax
tenant_purchase|access|Venta de vivienda pública a inquilinos|500 viviendas · descuento de prueba|10000000|250000|8|1|1|-1|1|1,2,3,2,0,0|Facilitar propiedad de adjudicatarios reduce parque público de alquiler si no se repone|Acceso de inquilinos adjudicatarios|Pérdida patrimonial y menos oferta social futura|oecd_reform
transaction_tax_cut|tax|Reducir ITP y AJD para primera vivienda|100 % de operaciones elegibles|300000|5000000|20|0|0|1|0|2,2,0,5,2,1|Reducir coste de transacción facilita movilidad y puede elevar precio antes de impuestos|Menor desembolso de acceso|Menos recaudación y capitalización|oecd_tax
supply_tax_cut|tax|Bonificar ICIO y tasas de nueva oferta|100 % de promociones elegibles|300000|3000000|12|6|-1|-1|-1|2,5,2,3,1,0|Reducir tributos de promoción mejora viabilidad sin garantizar que todo ahorro llegue al comprador|Incentivo a producir|Ingreso municipal sacrificado|oecd_tax,bde
vacancy_tax|tax|Recargo sobre vivienda vacía verificada|100 % de vacíos elegibles|1000000|500000|20|2|-1|-1|-1|-4,-3,3,2,1,0|Gravar desocupación injustificada incentiva uso solo donde hay demanda|Movilizar parte del parque vacío|Definición de vacío y coste de inspección|oecd_tax,law_housing
land_tax|tax|Fiscalidad del valor del suelo|100 % de parcelas elegibles|3000000|600000|20|4|-1|-2|-1|-3,-4,2,3,1,-2|Gravar suelo más que mejoras desincentiva retención y favorece uso intensivo|Menor incentivo a mantener suelo improductivo|Valoración y transición para propietarios con poca renta|oecd_tax
anti_flip|tax|Recargo a reventas especulativas cortas|100 % de operaciones elegibles|800000|250000|12|1|0|-1|0|-2,-6,1,2,1,-1|Desincentivar reventa rápida puede contener rotación especulativa y reducir liquidez|Menos demanda de corto plazo|Bloqueo de transacciones y excepciones necesarias|oecd_tax
tourist_days|demand|Limitar días de alquiler turístico|100 % de áreas elegibles|1200000|600000|20|2|-2|-1|-2|-3,-5,4,2,1,4|Reducir uso turístico puede retornar viviendas si se fiscaliza y existe demanda residencial|Menor presión en áreas turísticas|Ingreso turístico perdido y desplazamiento geográfico|str,bde_rent
tourist_licenses|demand|Moratoria de nuevas licencias turísticas|100 % de zonas elegibles|700000|400000|12|1|-1|-1|-1|-1,-3,2,1,0,2|Frenar nuevas conversiones preserva oferta sin recuperar automáticamente la existente|Evitar nuevas salidas del residencial|Beneficio a licencias existentes y competencia reducida|str
seasonal_checks|demand|Inspeccionar falsos alquileres de temporada|100 % de expedientes de riesgo|1000000|900000|20|1|-1|0|-1|-3,-2,3,1,0,1|Comprobar uso real reduce vías de elusión del alquiler habitual|Cumplimiento más homogéneo|Fiscalización y clasificación litigiosa|bde_rent,str
foreign_surcharge|demand|Recargo a compra no residente|100 % de operaciones elegibles|1200000|400000|12|1|0|-2|0|-2,-4,1,3,-7,0|Menor demanda no residente puede aliviar compra; nacionalidad y residencia son distintas|Menor competencia en compra en áreas expuestas|Riesgo jurídico y posible caída de inversión|capital,eu_proposal
foreign_ban|demand|Restricción temporal de compra extranjera|100 % de operaciones elegibles|2000000|600000|8|1|1|-3|1|-3,-6,0,4,-12,-1|Hipótesis extrema: restringir demanda reduce competencia pero puede frenar promoción financiada externamente|Alivio de demanda en compraventa|Compatibilidad europea muy incierta y oferta afectada|capital,eu_proposal
student_housing|demand|Residencias de estudiantes y trabajadores|1000 plazas|10000000|3000000|12|8|-1|0|-1|0,3,3,1,0,1|Alojamiento especializado reduce competencia por pisos familiares si cubre necesidad real|Liberar demanda residencial convencional|Coste y ubicación adecuada|oecd_actions,plan2026
transit|territory|Mejorar transporte hacia zonas asequibles|100 % del programa de prueba|20000000|3000000|20|8|-1|-1|-1|1,2,3,3,1,3|Conectividad amplía opciones y desplaza demanda; puede encarecer destinos conectados|Más acceso a empleo y vivienda|Coste y capitalización en suelo de destino|oecd_reform
rural_incentive|territory|Incentivos a residencia y actividad rural|5000 hogares y negocios|1000000|5000000|20|6|-1|-1|-1|0,1,2,2,1,1|Beneficio fiscal ligado a residencia real puede desplazar demanda si hay empleo y servicios|Desconcentración potencial|Gasto fiscal y efecto pequeño sin oportunidades|oecd_actions,bde
remote_work|territory|Conectividad y teletrabajo territorial|100 % de áreas del programa|10000000|1000000|16|6|-1|-1|-1|0,2,2,2,1,2|Acceso digital permite movilidad de parte de empleos, no de todos|Más opciones residenciales|Desigualdad de acceso y presión en destinos|oecd_reform
'''
measures=[]
gnames=['Propietarios','Inversores','Inquilinos','Compradores nacionales','Compradores extranjeros','Propietarios residentes']
reasons={
'controls':['Renta y derechos de gestión de las viviendas cubiertas','Retorno esperado y capacidad de cambiar de uso','Protección de beneficiarios frente a dificultad de los nuevos demandantes','Oferta de compra y cambios desde alquiler hacia venta','Acceso a compra y exposición a retorno o restricciones','Efectos indirectos sobre vecindario y valor patrimonial'],
'admin':['Costes y plazos de mejora o puesta en alquiler','Viabilidad y duración de los proyectos','Oferta nueva después de la ejecución','Más promociones y menor coste de tramitación','Acceso a proyectos y menor incertidumbre','Calidad de controles, obras y servicios del entorno'],
'supply':['Competencia de nueva oferta y calidad del parque','Oportunidades de promoción frente a presión sobre márgenes','Disponibilidad futura y acceso al parque asequible','Oferta futura y precios de entrada','Acceso a nueva oferta y oportunidades de inversión','Servicios, valor patrimonial e impacto del desarrollo'],
'mobilise':['Calidad de activos, seguridad de cobro y costes','Rentabilidad de mejora y oportunidades de inversión','Calidad y disponibilidad de alquiler habitual','Oferta de compra y competencia pública por activos','Oferta y competencia por activos','Habitabilidad y autonomía en su vivienda'],
'access':['Demanda solvente, seguridad de cobro y obligaciones','Demanda y retorno esperado','Acceso y protección de los hogares beneficiarios','Entrada necesaria y competencia en compra','Elegibilidad y cambios indirectos de precios','Fiscalidad y apoyo a vivienda habitual'],
 'tax':['Ingreso neto, obligaciones y coste de mantener activos','Retorno después de impuestos y liquidez','Oferta resultante y traslado parcial de costes','Coste total de acceso y movilidad','Impuestos y acceso a operaciones','Carga patrimonial y posibilidad de cambiar de vivienda'],
 'demand':['Cambios de uso, ingresos turísticos y seguridad jurídica','Retorno y restricciones a segmentos de demanda','Vivienda disponible para alquiler habitual','Competencia por las viviendas ofrecidas','Elegibilidad: residencia y nacionalidad requieren distinción','Convivencia y actividad económica del barrio'],
 'territory':['Demanda y rentas en origen y destino','Oportunidades en nuevas localizaciones','Opciones de acceso a empleo y vivienda','Mercado más amplio de búsqueda','Opciones territoriales disponibles','Conectividad y servicios públicos del entorno']}
for line in raw.strip().splitlines():
 a=line.split('|');id,cat,name,full,initial,quarter,duration,delay,rent,sale,free,hs,mechanism,pro,con,refs=a
 h=list(map(float,hs.split(',')))
 m=dict(id='a2_'+id,category=cat,name=name,full_application=full,initial_cost=int(initial),quarterly_cost=int(quarter),duration_turns=int(duration),delay_turns=int(delay),happiness=h,price={'rent':float(rent),'sale':float(sale),'free_rent':float(free)},mechanism=mechanism,pros=[pro],cons=[con],sources=refs.split(','),curve='saturating',permanent=cat in ['supply','mobilise'] and id not in ['rental_guarantee','mediation'],exclusive_group='rent_control' if cat=='controls' and id!='protected_sale' else 'admin_level' if id.startswith('admin_') and id!='admin_staff' else None,risk_high=cat in ['controls','demand'] or id in ['admin_risk','building_code','rural_land'],legal_status='hypothetical_review_required' if id in ['foreign_ban','foreign_surcharge','income_cap','cost_return','rural_land','land_tax'] else 'design_subject_to_legal_review',coefficient_status='game_assumption_not_empirical_estimate',unit_cost_status='estimate',competencies=['national','regional'] if cat=='controls' else ['local','regional'] if cat in ['admin','supply','mobilise'] else ['national','regional','local'])
 m['rationales']=[r+'. '+('Beneficio potencial' if v>0 else 'Perjuicio potencial' if v<0 else 'Efecto directo limitado')+' antes de financiación.' for r,v in zip(reasons[cat],h)]
 if id=='public_build':
  m['cost_breakdown']={'construction_per_home':180000,'land_per_home':40000,'urbanisation_and_project_per_home':20000,'homes_at_full':1000,'construction_band':[140000,220000],'annual_maintenance_per_home':2000,'note':'Estimación 2026; suelo e infraestructura son supuestos. Referencias 2023–2024 incluyen otros usos. No son tarifas por ciudad.'};m['unit_cost_status']='estimate_anchored_to_observed_projects'
 if id in ['energy_rehab','accessibility','rent_aid_target','rent_aid_universal']:m['unit_cost_status']='aid_reference_or_chosen_amount_not_total_project_cost'
 if id=='mortgage_guarantee':m['cost_breakdown']={'homes':2000,'loan':250000,'guarantee_share':0.2,'guaranteed_exposure':100000000,'expected_loss_assumption':0.05,'cash_reserve':5000000,'note':'Aval de 100 M€ no equivale a gasto de 100 M€. Reserva de pérdidas del 5 % es supuesto.'}
 measures.append(m)
# Annual historical references. Sandbox allocation 1% is NOT a municipal budget or an actual transferable amount.
B=[('pensions','Pensiones',190687246150,[-4,-4,-5,-4,-3,-10]),('health','Sanidad',7049082760,[-5,-5,-8,-6,-5,-8]),('education','Educación',5354973350,[-3,-3,-7,-7,-4,-5]),('social','Servicios sociales y promoción social',7116821580,[-2,-2,-10,-5,-4,-7]),('employment','Fomento del empleo',8028785390,[-2,-3,-6,-7,-3,-3]),('unemployment','Desempleo',21278019880,[-2,-2,-10,-6,-3,-3]),('culture','Cultura',1803749820,[-2,-2,-3,-3,-2,-3]),('defence','Defensa',12316829070,[-1,-1,-1,-1,-1,-1]),('security','Seguridad ciudadana',10719209470,[-4,-4,-4,-4,-3,-5]),('infrastructure','Infraestructuras y ecosistemas resilientes',12644589580,[-4,-5,-6,-6,-3,-5]),('research','I+D+i y digitalización',17766985030,[-2,-4,-4,-4,-2,-3]),('transport','Subvenciones al transporte',3447680300,[-2,-2,-7,-6,-3,-5])]
T=[('irpf','IRPF',113123000000,[-5,-4,-5,-6,-2,-5]),('iva','IVA nacional',86093000000,[-4,-4,-8,-7,-4,-6]),('corporate','Impuesto sobre Sociedades',28519000000,[-1,-9,-2,-2,-3,-1]),('excise','Impuestos especiales',22287000000,[-3,-3,-5,-5,-3,-4]),('nonresident','IRNR',2681000000,[-1,-4,-1,-1,-10,0])]
funds=[]
for id,name,annual,h in B:
 funds.append(dict(id='a2_cut_'+id,name=name,kind='spending_cut',annual_reference=annual,reference_year=2023,scope='PGE aprobado, consolidado capítulos 1–9; no gasto total de todas las administraciones',sandbox_share=0.01,max_adjustment=0.2,response=1,happiness=h,sources=['pge_spending','civio'],consequences='Reducir esta política sacrifica servicios y prestaciones. Impactos de felicidad son hipótesis del juego; cada grupo incluye usuarios distintos.'))
for id,name,annual,h in T:
 funds.append(dict(id='a2_tax_'+id,name=name,kind='tax_increase',annual_reference=annual,reference_year=2023,scope='Previsión nacional antes de cesiones territoriales, no liquidación',sandbox_share=0.01,max_adjustment=0.10,response=0.7,happiness=h,sources=['pge_tax','civio'],consequences='Incremento relativo del esfuerzo fiscal. La respuesta de recaudación del 70 % es supuesto; no son puntos de tipo legal ni una previsión fiscal.'))
# Additional territorial taxes need territorial data: not fabricate national amounts for IBI, ITP, AJD, IGIC.
notes={'created':'2026-10-01','version':'alpha-2','sources':sources,'categories':categories,'groups':gnames,'group_ids':['landlords','investors','tenants','domestic_buyers','foreign_buyers','resident_owners'],'weights':[18,12,28,18,9,15],'measures':measures,'funding_sources':funds,'methodology':{'effects':'Todos los coeficientes son hipótesis alfa propias, no estimaciones extraídas de las fuentes. Horizonte objetivo de 5 años, condicionado a demora y maduración.','curve':'f(x)=(1-exp(-2*x))/(1-exp(-2)); f(0)=0, f(1)=1. Riesgo extra por encima del 75 %.','budget':'Base histórica PGE 2023, cartera experimental del 1 % de cada partida. Escala arbitraria visible, no presupuesto municipal. Cuentas de impuestos antes de cesiones no se suman a gasto para fingir un presupuesto consolidado.','costs':'Euros nominales de referencias históricas o supuestos 2026. Construcción anclada a promociones públicas; no se confunden ayudas máximas con coste total.','taxes_pending':'IBI, ITP, AJD, Patrimonio y, en Canarias, IGIC requieren una base territorial comparable. No se inventan recaudaciones para ellos.','democracy':'Inspiración verificable en sliders, efectos no lineales, colectivos y retrasos. No se afirma haber auditado todos los DLC ni el catálogo binario completo de Democracy 3.'}}
from simulator_national import nationalise
notes=nationalise(notes)
from simulator_audit import audit
notes=audit(notes)
Path('data/simulator/catalog.json').write_text(json.dumps(notes,ensure_ascii=False,indent=2)+'\n')
Path('data/simulator/catalog.js').write_text('window.SIM_CATALOG = '+json.dumps(notes,ensure_ascii=False)+';\n')
print(f"{len(notes['measures'])} measures, {len(notes['funding_sources'])} funding sources, {len(notes['sources'])} references")
