const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),M=require('../assets/simulator/model-config'),H=require('../assets/simulator/housing-policy');
const pack=M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json'))),D=M.toCatalog(pack),idx=id=>D.measures.findIndex(m=>m.id===id),act=(key,intensity=1,extra={})=>({index:idx('a3_migration_'+key),start:1,intensity,funding:[],shares:{},...extra});
assert.deepEqual(M.validate(pack),[]);assert.deepEqual(M.fromCatalog(D),pack);
const migrants=D.measures.filter(m=>m.category==='migration');assert.equal(migrants.length,8);assert.equal(idx('a3_migration_integration'),-1);
for(const m of migrants){assert.ok(m.sources.length);assert.equal(m.effects.filter(e=>e.target_type==='group'&&e.target_id==='foreign_buyers').reduce((n,e)=>n+e.amount,0),0,'Nonresident buyers are not migrants');if(m.migration_program){assert.equal(m.budget_control.period,'annual');assert.ok(m.selection_description.split('. ').length>=3);}}
const ret=act('return',1,{return_bonus:30000}),zero={...ret,return_bonus:0},half={...ret,intensity:.5},rm=act('removals');
assert.ok(H.migrationCapacity(D.measures[ret.index],ret)>H.migrationCapacity(D.measures[zero.index],zero));assert.equal(H.migrationCapacity(D.measures[half.index],half)*2,H.migrationCapacity(D.measures[ret.index],ret));
assert.equal(H.costs(D.measures[zero.index],zero).quarter,62500000);assert.equal(H.costs(D.measures[ret.index],ret).bonusQuarter,375000000);assert.equal(H.costs(D.measures[ret.index],ret).quarter,437500000,'Bonus must be financed in addition to administration');
assert.ok(H.migrationConflicts(D,[{...ret,return_bonus:30100}]).length);assert.ok(H.programmeConflicts(D.measures,[rm,{...rm,start:2}]).length);
const actions=[];for(let start=1;start<=73;start+=12)actions.push({...rm,start},{...ret,start});const pipe=H.migrationPipeline(D,80,actions);assert.ok(pipe.departures<=400000);assert.ok(pipe.departures>0);assert.equal(pipe.emigration_per_year,0,'Shared finite departure pool exhausted');
for(const mutate of [m=>m.migration_program.bonus.default=30001,m=>m.migration_program.eligible_pool=0,m=>m.migration_flows.emigration_per_year=NaN]){const bad=M.clone(pack);mutate(bad.model.measures.find(m=>m.id==='a3_migration_return'));assert.ok(M.validate(bad).length);}
function engine(model){const d=model?M.toCatalog(pack):JSON.parse(fs.readFileSync('data/simulator/catalog.json')),nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{style:{setProperty(){}},dataset:{},setAttribute(){},showModal(){},close(){},hidden:false});return nodes.get(id)},c=vm.createContext({window:{SIM_CATALOG:d,SIM_MODEL:M},Intl,structuredClone,document:{getElementById:node,querySelector:node}});for(const f of ['housing-policy','national','fiscal','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),c);return {d,node,run:s=>vm.runInContext(s,c)};}
for(const mode of [false,true]){const {run,node}=engine(mode),sim=(key,t,intensity=1,extra={})=>run(`outcome(${t},${key?JSON.stringify([act(key,intensity,extra)]):'[]'})`);
 const base=sim(null,12),regular=sim('regularise',12),relocate=sim('interior',12);assert.equal(regular[10],base[10]);assert.ok(regular[12]>base[12],'Existing residents can increase effective rental searches');assert.equal(relocate[10],base[10]);assert.equal(relocate.diagnostics.availableHomes,base.diagnostics.availableHomes,'Relocation creates no housing stock');
 const end=sim('return',12,1,{return_bonus:30000}),after=sim('return',20,1,{return_bonus:30000});assert.ok(end[10]<base[10]);assert.ok(Math.abs(after.diagnostics.migrationPopulationDelta-end.diagnostics.migrationPopulationDelta)<.01);assert.equal(after.diagnostics.flows.emigration,after.diagnostics.officialFlows.emigration);
 assert.ok(sim('return',12,1,{return_bonus:30000})[10]<sim('return',12,1,{return_bonus:0})[10]);assert.ok(sim('return',12,1,{return_bonus:30000})[9]<base[9],'Departure loss outweighs administrative activity; foreign bonus is not domestic production');assert.ok(sim('removals',12)[9]<base[9]);assert.ok(sim('removals',12)[12]<base[12]);assert.ok(sim('permits_limit',12)[10]<base[10]);assert.equal(sim('removals',2)[10],sim(null,2)[10]);
 for(const m of migrants)for(const intensity of [.01,.5,1]){const v=sim(m.id.slice('a3_migration_'.length),80,intensity);assert.ok(v.every(Number.isFinite),m.id);assert.ok(v.diagnostics.flows.immigration>=0&&v.diagnostics.flows.emigration>=0);}
 for(const [key,min,max]of [['removals',40,4000],['regularise',8,800],['permits_limit',4,400],['seasonal_housing',6,600],['interior',5,500],['return',2.5,250],['reception',20,2000]]){run(`openPolicy(${idx('a3_migration_'+key)})`);assert.equal(node('intensity-label').textContent,'Presupuesto anual');assert.equal(+node('intensity').min,min);assert.equal(+node('intensity').max,max);node('intensity').oninput({target:{value:String(min)}});assert.ok(run('draft.intensity')>0);}
 run(`openPolicy(${ret.index})`);assert.equal(node('enforcement-block').hidden,false);assert.equal(node('enforcement-label').textContent,'Bonificación por persona');node('enforcement').oninput({target:{value:'30000'}});assert.equal(run('draft.return_bonus'),30000);assert.equal(node('enforcement').max,30000);
}
console.log('PASS: migration budgets and bonus controls, funded bonus reserve, pool caps, overlapping programmes, persistent population/GDP, resident regularisation, internal relocation without fictitious stock, JSON roundtrip and validation, 80-turn finite scenarios in both engines.');
