/* Public release contract, syntax, references and privacy. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const M=require('../assets/simulator/model-config'),catalog=JSON.parse(fs.readFileSync('data/simulator/catalog.json')),pack=M.fromCatalog(catalog),release=JSON.parse(fs.readFileSync('data/simulator/public-release.json'));
assert.deepEqual(M.validate(pack),[]);assert.equal(crypto.createHash('sha256').update(JSON.stringify(pack)).digest('hex'),release.source_sha256,'Published model payload checksum');assert.equal(pack.metadata.version,release.model_version);assert.equal(pack.model.measures.length,release.measures);assert.equal(pack.comments.length,0);assert.ok(!pack.review_progress);assert.ok(release.model_version.includes('collective1'));
const context={window:{},Object};vm.runInNewContext(fs.readFileSync('assets/simulator/supabase-config.js','utf8'),context);assert.equal(context.window.SIM_SUPABASE.version,release.model_version);assert.ok(context.window.SIM_SUPABASE.publishableKey.startsWith('sb_publishable_'));
for(const [file,hash]of Object.entries(release.engine_manifest)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),hash,'Engine differs from published model: '+file);new vm.Script(fs.readFileSync(file,'utf8'),{filename:file});}
vm.runInNewContext(fs.readFileSync('data/simulator/catalog.js','utf8'),{window:{}});
const pages=['index.html','boceto_portal.html','simulador_total.html','vivienda_simulator.html','mapa_desarrollo_urbano.html','mapa_fiscalidad_mejorada.html'];
for(const file of pages){const html=fs.readFileSync(file,'utf8');assert.ok(!/href=["'][^"']*\.md(?:[?#"'])/i.test(html),file+' links internal Markdown');assert.ok(!/simulator_control\.html|vivienda_revision_/.test(html),file+' links internal review');for(const [,source]of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))if(source.trim())new vm.Script(source,{filename:file});for(const [,url]of html.matchAll(/(?:src|href)=["']([^"']+)["']/g)){if(/^(?:https?:|data:|mailto:|tel:|javascript:|#)/i.test(url))continue;const local=url.split(/[?#]/)[0];if(!local)continue;assert.ok(fs.existsSync(path.resolve(path.dirname(file),local)),file+' missing '+local);}}
console.log('PASS: public model '+release.model_version+', '+release.measures+' measures, exact engine hashes, empty private notes, publishable API key, HTML syntax and local links.');
