const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),M=require('../assets/simulator/model-config');
const html=fs.readFileSync('vivienda_simulator.html','utf8');
assert.ok(!html.includes('id="open-fiscal"'),'Fiscal controls must not be available globally');
assert.equal((html.match(/id="policy-fiscal"/g)||[]).length,0,'There is no global fiscal control outside a measure');
assert.equal((html.match(/id="fiscal-dialog"/g)||[]).length,0,'The obsolete global fiscal dialog is removed');
assert.ok(html.includes('id="funding-all"')&&html.includes('id="funding-fill"'),'A measure offers direct allocation to a selected source');
assert.ok(!html.includes('id="funding-auto"'),'Automatic funding allocation is removed');
assert.ok(html.includes('class="policy-outlook"'),'The policy response uses the compact direct-effects panel');
assert.ok(!html.includes('id="about"'),'The redundant About the game button stays removed');
assert.ok(html.includes('class="roadmap-infographic"'),'Development roadmap is rendered as an infographic');
assert.ok(html.includes('Running on autism and caffeine'),'Simulator footer uses the current signature');
const d=M.toCatalog(M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json')))),nodes=new Map(),c=vm.createContext({window:{SIM_CATALOG:d,SIM_MODEL:M},Intl,structuredClone,document:{getElementById(id){if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);}}});
for(const f of ['housing-policy','national','fiscal','turn-report','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),c);
const run=s=>vm.runInContext(s,c);
run("fiscalEvents=[{turn:0,levels:{}}]");const baseline=run('housingOutcome(1,[])');
run("fiscalEvents.push({turn:1,levels:{a3_tax_irpf:14.1}})");const cut=run('housingOutcome(1,[])');assert.ok(cut[2]<baseline[2],'IRPF cut increases tenant happiness');assert.ok(run("fiscalCheck({a3_tax_irpf:14.1},[]).length>0"),'Tax cuts cannot be unfunded');
assert.equal(run("fiscalCheck({a3_tax_irpf:14.1,a3_cut_pensions:180000},[])"),'','Offset tax cut can advance');
run("fiscalEvents=[{turn:0,levels:{}},{turn:1,levels:{a3_cut_health:110000}}]");assert.ok(run('housingOutcome(1,[])[2]')<baseline[2],'Health expansion improves group happiness');assert.ok(run("fiscalAmount(D.funding_sources.find(s=>s.id==='a3_cut_health'),{a3_cut_health:110000},1)")<0,'Spending expansion consumes money');
assert.ok(run("fiscalCheck({a3_cut_health:110000},[]).length>0"),'Spending expansion must be funded');
run("fiscalEvents=[{turn:0,levels:{}},{turn:2,levels:{a3_tax_iva:20}},{turn:5,levels:{a3_tax_iva:21}}]");assert.equal(run("fiscalValue(D.funding_sources.find(s=>s.id==='a3_tax_iva'),fiscalLevels(1))"),21);assert.equal(run("fiscalLevels(4).a3_tax_iva"),20);assert.equal(run("fiscalLevels(5).a3_tax_iva"),21);
assert.ok(run('outcome(8,[]).every(Number.isFinite)'));
run('turn=6;history=Array.from({length:7},(_,i)=>outcome(i,[]))');const chart=run('reportEvolution(reportMetrics(history[5],history[6]).slice(0,3),false)');assert.equal((chart.match(/<circle /g)||[]).length,15,'Three overlaid series × five quarterly observations');assert.equal((chart.match(/<svg /g)||[]).length,1);assert.equal((chart.match(/<polyline /g)||[]).length,3);assert.ok(!chart.includes('NaN'));assert.ok(chart.includes('T2 · 2027'),'Rolling window starts at correct quarter');
assert.equal(d.funding_sources.find(s=>s.id==='a3_cut_pensions').name,'Pensiones');
assert.equal(d.funding_sources.find(s=>s.id==='a3_tax_iva').name,'IVA');
run('turn=0;active=[];planned.clear();fiscalEvents=[{turn:0,levels:{}}];draft={index:0,intensity:.5,start:1,shares:{a3_tax_iva:-1000,a3_cut_pensions:1100},funding:[]};readFunding()');
assert.ok(run('draft.funding.find(f=>f.source_id==="a3_tax_iva").quarterly_amount<0'),'A tax reduction is retained as a negative financing flow');
assert.equal(run('fiscalBalance({},1,[draft])'),0,'Positive financing offsets the policy and the tax reduction exactly');
assert.equal(run('draft.funding.reduce((n,f)=>n+f.quarterly_amount,0)'),run('costs(D.measures[draft.index],draft.intensity).quarter'),'Recurring flows remain balanced');
assert.equal(run('sourceCurrentValue(D.funding_sources.find(s=>s.id==="a3_tax_iva"))'),21,'An untouched VAT bar starts at the current rate');
run('turn=6');
run('active=[{index:0,intensity:.5,start:1,funding:[]}];fiscalEvents=[{turn:0,levels:{}},{turn:1,levels:{a3_tax_iva:22}}]');
const details=run('finalReportDetails(reportMetrics(history[0],history[turn]))');
assert.ok(details.includes('Historial completo de medidas')&&details.includes('Felicidad: valores y ponderaciones'));
assert.ok(details.includes('Compromisos al cerrar')&&details.includes('Anuncios de alquiler estimados'));
assert.ok(!details.includes('NaN')&&!details.includes('undefined'));
assert.ok(run('finalFiscalTotals().cost>0'));
assert.equal(run('finalFiscalTotals().balance'),run('finalFiscalTotals().financed-finalFiscalTotals().cost'));
assert.ok(run('finalReportOpening(reportMetrics(history[0],history[turn]))').includes('final-balance-grid'));
console.log('PASS: policy-only fiscal access, bidirectional fiscal flows, persistent single-source mosaic editor, deficit guard, overlaid quarterly chart and complete final report with reconciled fiscal totals.');
