const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),M=require('../assets/simulator/model-config'),H=require('../assets/simulator/housing-policy');
const pack=M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json'))),D=M.toCatalog(pack),by=id=>D.measures.find(m=>m.id===id),idx=id=>D.measures.findIndex(m=>m.id===id),act=(id,intensity=1,extra={})=>({index:idx(id),start:1,intensity,funding:[],shares:{},...extra});
assert.deepEqual(M.validate(pack),[]);assert.deepEqual(M.fromCatalog(D),pack);assert.equal(by('a3_rural_incentive'),undefined);
const rural=by('a3_rural_tax_zones'),r=act(rural.id,1,{tax_rates:{irpf:0,corporate:0},tax_bases:{irpf:15.1,corporate:25}}),irpfOnly={...r,tax_rates:{irpf:0,corporate:25}},normal=act('a3_legal_aid',1,{funding:[{source_id:'a3_tax_irpf',initial_amount:0,quarterly_amount:100000000}]});
assert.equal(H.fundingScopeFraction(D,'a3_tax_irpf',1,[r]),.97);assert.equal(H.fundingScopeFraction(D,'a3_tax_corporate',1,[irpfOnly]),1);assert.equal(H.fundingScopeFraction(D,'a3_tax_corporate',1,[r]),.98);assert.equal(H.fundingScopeFraction(D,'a3_tax_irpf',21,[r]),1);assert.equal(H.fiscalConflicts(D.measures,[r,normal]).length,0);assert.ok(H.fiscalConflicts(D.measures,[r,{...r,start:2}]).length);
assert.ok(M.policyAt(D,rural,irpfOnly,12,[irpfOnly]).groups.tenants>M.policyAt(D,rural,{...r,tax_rates:{irpf:15.1,corporate:0}},12,[r]).groups.tenants,'Separate IRPF and IS effects');
const plan=by('a3_strategic_urban_agency'),a=act(plan.id),transit=by('a3_transit'),tr=act(transit.id),digital=by('a3_remote_work'),di=act(digital.id);
assert.equal(H.territoryAt(plan,a,31).completed,0);assert.equal(H.territoryAt(plan,a,52).completed,245000);assert.equal(H.territoryAt(plan,act(plan.id,.005),52).completed,1225);assert.equal(H.territoryAt(plan,a,80).completed,245000);assert.equal(H.territoryAt(transit,tr,15).accessible,0);assert.equal(H.territoryAt(transit,tr,40).accessible,1000000);assert.equal(H.territoryAt(transit,tr,40).completed,0);assert.equal(H.territoryAt(digital,di,3).progress,0);assert.equal(H.territoryAt(digital,di,12).progress,1);
assert.equal(H.costs(transit,tr).quarter*4,10000000000);assert.equal(H.costs(transit,act(transit.id,.001)).quarter*4,10000000);assert.equal(H.costs(digital,di).quarter*4,125000000);assert.equal(H.costs(digital,act(digital.id,.008)).quarter*4,1000000);assert.equal(H.costs(plan,a).quarter*4,2000000000);assert.equal(M.policyAt(D,plan,a,20,[a]).price.rent,0);assert.equal(M.policyAt(D,plan,a,52,[a]).price.rent,0,'Housing supply determines the price');assert.equal(H.territorialShift(D,40,[tr]).households,1000000);assert.equal(H.territorialShift(D,12,[di]).households,50000);assert.ok(H.programmeConflicts(D.measures,[a,{...a,start:2}]).length);assert.ok(H.programmeConflicts(D.measures,[a,{...a,start:30}]).length);
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{style:{setProperty(){}},dataset:{},textContent:'',setAttribute(k,v){this[k]=v;},showModal(){},labels:[{}],querySelectorAll(){return[]},insertAdjacentHTML(){},focus(){}});return nodes.get(id);},opened=[],ctx=vm.createContext({window:{SIM_CATALOG:D,SIM_MODEL:M,open:(...args)=>opened.push(args)},Intl,structuredClone,document:{getElementById:node,querySelector:()=>node('methodology')}});for(const f of ['housing-policy','national','fiscal','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),ctx);const run=s=>vm.runInContext(s,ctx);Object.assign(ctx,{r,normal,a,tr,di});run('renderFunding=()=>{};history=[initialState()]');
run(`openPolicy(${idx(rural.id)})`);assert.equal(+node('intensity').value,15.1);assert.ok(node('tax-extra-controls').innerHTML.includes('Tipo rural de Impuesto sobre Sociedades'));assert.equal(node('rural-tax-warning').hidden,false);run("draft.tax_rates={irpf:0,corporate:0};draft.intensity=H.taxForce(D.measures[draft.index],draft);draft.shares={'a3_tax_irpf':100};updateDraft();readFunding()");assert.equal(run("draft.funding.find(f=>!f.locked).scope_fraction"),.97);assert.equal(run("H.taxRate(D.measures[draft.index].tax_control.components[0],draft)"),0);assert.ok(run("sourceDraftValue(D.funding_sources.find(s=>s.id==='a3_tax_irpf'))")>15.1);assert.ok(run("sourceShareBounds(D.funding_sources.find(s=>s.id==='a3_tax_irpf')).max")>0);assert.equal(run('validateDraft().length'),0);assert.ok(Math.abs(run('fiscalBalance({},1,[draft])'))<.02,'Self-finance general IRPF outside protected zones reconciles');
run('active=[structuredClone(draft)];draft={index:0,intensity:1,funding:[],shares:{}}');assert.ok(run("sourceCurrentValue(D.funding_sources.find(s=>s.id==='a3_tax_irpf'),2)")>15.1);run('active=[]');assert.equal(run('amountFor(normal,D.funding_sources.find(s=>s.id===\'a3_tax_irpf\'),2,[normal,r])'),97000000,'Already approved general rise loses eligible rural receipts');
assert.equal(run('fiscalUsed(D.funding_sources.find(s=>s.id===\'a3_tax_irpf\'),2,[{...normal,funding:[{...normal.funding[0],scope_fraction:.97}]},r])'),100000000,'Scope-adjusted new financing is not discounted twice');
run('active=[{...r,funding:[{source_id:\'a3_tax_irpf\',initial_amount:0,quarterly_amount:-D.funding_sources.find(s=>s.id===\'a3_tax_irpf\').annual_reference*.03/4,locked:true}]}]');assert.ok(Math.abs(run("sourceCurrentValue(D.funding_sources.find(s=>s.id==='a3_tax_irpf'),2)")-15.1)<1e-9,'Rural cut alone does not change general tax rate');run('active=[]');
for(const [m,min,max]of [[plan,10,2000],[transit,10,10000],[digital,1,125]]){run(`openPolicy(${idx(m.id)})`);assert.equal(node('intensity-label').textContent,'Presupuesto anual');assert.equal(+node('intensity').min,min);assert.equal(+node('intensity').max,max);node('intensity').oninput({target:{value:String(min)}});assert.ok(run('draft.intensity')>0);}
const length=run('history.length');run("openInfo('measure:a3_rural_tax_zones')");run("openInfo('measure:a3_strategic_urban_agency')");assert.deepEqual(opened,[['mapa_fiscalidad_mejorada.html','_blank','noopener'],['mapa_desarrollo_urbano.html','_blank','noopener']]);assert.equal(run('history.length'),length);
assert.equal(run('outcome(31,[a])[15]'),run('outcome(31,[])[15]'),'Urban agency creates no homes before construction delay');assert.ok(run('outcome(52,[a])[15]')>run('outcome(52,[])[15]'));assert.equal(run('outcome(40,[tr])[15]'),run('outcome(40,[])[15]'),'Transport adds accessibility, not physical homes');
const bad=M.clone(pack);bad.model.measures.find(m=>m.map_reference).map_reference.path='javascript:alert(1)';assert.ok(M.validate(bad).length);const orphan=M.clone(pack);orphan.model.measures.find(m=>m.id===rural.id).tax_control.components[0].protected_scope='broken';assert.ok(M.validate(orphan).length);console.log('PASS: independent protected rural taxes, general-rate exception and historical revenue adjustment, scope-aware finance reconciliation, map new windows without state loss, budget extremes, delayed urban housing, transport without fictitious homes, limited digital effects, no duplicate programmes and validation/roundtrip.');
