/* Causal regressions: isolate channels, then test financed decisions in the actual engine. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const M=require('../assets/simulator/model-config'),H=require('../assets/simulator/housing-policy'),pack=M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json')));
const clone=M.clone,D=M.toCatalog(pack),checks=[],evidence={version:pack.metadata.version,checks,samples:{}};
function ok(value,name){assert.ok(value,name);checks.push(name)}
function engine(input=pack){const d=M.toCatalog(input),nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{style:{setProperty(){}},dataset:{},setAttribute(){},showModal(){},close(){},hidden:false});return nodes.get(id)},ctx=vm.createContext({window:{SIM_CATALOG:d,SIM_MODEL:M},Intl,structuredClone,document:{getElementById:node,querySelector:node}});for(const f of ['housing-policy','national','fiscal','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),ctx);return {d,ctx,run:s=>vm.runInContext(s,ctx),at(t,a=[]){ctx.acts=a;ctx.t=t;return vm.runInContext('outcome(t,acts)',ctx)}}}
const E=engine(),action=(id,intensity=1,extra={})=>({index:D.measures.findIndex(m=>m.id===id),start:1,intensity,funding:[],...extra}),measure=a=>D.measures[a.index];
// Direct sale price, with all other effects removed: final affordability must react.
const isolated=clone(pack),m=isolated.model.measures[0];delete m.price_control;m.effects=[{id:'price_only',target_type:'price',target_id:'sale',amount:-10,operation:'percent',delay_turns:0,maturation_turns:0,duration_turns:80,permanent:false,requires:[]}];const I=engine(isolated),ib=I.at(4),iv=I.at(4,[action(m.id)]);
ok(iv[7]<ib[7]&&iv[3]<ib[3]&&iv[4]<ib[4],'Sale-price-only reduction improves both purchaser groups');evidence.samples.sale_only={price_change_pct:(iv[7]/ib[7]-1)*100,buyer_happiness_gain:ib[3]-iv[3]};
// Withdrawal alone, identical regulation/costs/coefficients.
const freeze=action('a3_freeze',.8),noWithdrawal=clone(pack);noWithdrawal.model.measures[freeze.index].price_control.withdrawal_at_full=0;const W=engine(noWithdrawal),withW=E.at(4,[freeze]),withoutW=W.at(4,[freeze]);ok(withW.market.rent<withoutW.market.rent&&withW[8]>withoutW[8],'Withdrawn listings increase uncovered rent through the market');ok(withW[2]>withoutW[2],'Withdrawn listings worsen tenant search/affordability');ok(Math.abs(withW[6]-withoutW[6])<Math.abs(withW[8]-withoutW[8]),'Regulated incumbents are partly shielded from shortage');ok(E.at(20,[freeze]).market.rent===E.at(20).market.rent,'Temporary withdrawal recovers after expiry');
const protectedSale=action('a3_protected_sale'),pe=M.policyAt(D,measure(protectedSale),protectedSale,8,[protectedSale]);ok((pe.variables.rent_demand?.percent||0)===0,'Protected-sale regulation does not inherit rental demand coefficients');ok(Math.abs(pe.variables.gdp?.percent||0)<.01,'Five-percent coverage limits protected-sale macro effects');
const workers=action('a3_migration_construction'),early=H.privatePipeline(D,4,[workers]),late=H.privatePipeline(D,24,[workers]);ok(early.completed===0&&late.completed>0&&late.workers>0,'Construction workers create homes after a capacity/delivery lag');ok(late.completed<=D.rules.coherence.private_lifetime_extra_homes,'Private labour response has a finite capacity');
const insurance=action('a3_rental_guarantee',.5),im=measure(insurance),ic=H.costs(im,insurance);ok(ic.initial>ic.gdpInitial&&ic.reserveInitial>0,'Insurance reserves are financed without being counted as GDP services');const reserve=clone(im);reserve.insurance_program.reserve_months*=2;const rc=H.costs(reserve,insurance);ok(rc.initial>ic.initial&&rc.gdpInitial===ic.gdpInitial,'Increasing only insurance reserves leaves initial GDP expenditure unchanged');
const sell=action('a3_tenant_purchase',1,{beneficiaries:100000,management_intensity:1});const sold=E.at(80,[sell]),base80=E.at(80);ok(sold.diagnostics.coherence.publicStock.stock<base80.diagnostics.coherence.publicStock.stock,'Public stock remains lower after sales');ok(sold.diagnostics.coherence.waiting>base80.diagnostics.coherence.waiting&&sold[6]>base80[6],'Lost public rentals permanently affect waiting and average rent');
const regularise=action('a3_migration_regularise'),reception=action('a3_migration_reception'),migr=H.migrationPipeline(D,80,[regularise,reception]);ok([...migr.byAction.values()].reduce((a,b)=>a+b,0)<=500000,'Integration programmes share an eligible beneficiary pool');ok(H.migrationPipeline(D,20,[regularise]).immigration_per_year===0,'Regularisation never invents new population entries');const reverse=H.migrationPipeline(D,80,[reception,regularise]);ok(migr.byAction.get(regularise)===reverse.byAction.get(regularise),'Shared beneficiaries are allocated independently of UI order');ok(H.migrationPipeline(D,80,[reception]).activeByAction.get(reception)===undefined,'Temporary reception service does not last forever');
ok(Math.abs(D.display_groups.reduce((n,g)=>n+g.weight,0)-100)<1e-9&&D.display_groups.filter(g=>g.weight>0).length===6,'Social index weights every national group');ok(D.display_groups.find(g=>g.id==='foreign_buyers').weight===0,'Nonresident investors are excluded from the social index');
const pensions=D.funding_sources.find(s=>s.id==='a3_cut_pensions'),vat=D.funding_sources.find(s=>s.id==='a3_tax_iva'),cut=H.fiscalIncidence(D,pensions,100e6),tax=H.fiscalIncidence(D,vat,100e6),rebate=H.fiscalIncidence(D,vat,-100e6);ok(cut.income.resident_owners<cut.income.domestic_buyers,'Pension cuts follow pensioner exposure');ok(tax.income.tenants<0&&rebate.income.tenants>0,'Tax increases and cuts have opposite disposable-income effects');const zeroPension=clone(D);zeroPension.display_groups.find(g=>g.id==='resident_owners').profiles.pensioners=0;ok(H.fiscalIncidence(zeroPension,pensions,100e6).income.resident_owners===0,'Editing pensioner profile changes fiscal incidence');
const health=D.funding_sources.find(s=>s.id==='a3_cut_health'),hc=H.fiscalIncidence(D,health,100e6);ok(hc.income.tenants===0&&hc.groups.tenants<0,'Service loss is separate from cash income');
const adminActions=D.measures.filter(m=>m.admin_program).map(m=>action(m.id)),ap=H.adminPipeline(D,40,adminActions);ok([...ap.byAction.values()].reduce((n,x)=>n+x.completed,0)<=ap.completed+.01,'Administrative benefits use allocated completions');
const training=action('a3_training'),trained=H.privatePipeline(D,60,[training]);ok(trained.completed>0&&H.privatePipeline(D,4,[training]).completed===0,'Training changes private construction after delayed cost reductions');ok(H.privateInvestmentAt(D,24,[training],H.privatePipeline(D,24,[training]))>0,'Private additional construction contributes explicit investment');
const soil=action('a3_ppp_build'),sm=clone(measure(soil));sm.supply_program.private_finance_share=0;ok(H.supplyAt(sm,soil,80).completed===0&&H.supplyAt(measure(soil),soil,80).completed>0,'Private finance constrains public-land completion');sm.supply_program.private_finance_share=1;sm.supply_program.private_capital_at_full=0;ok(H.supplyAt(sm,soil,80).completed===0,'Zero private capital cannot deliver private construction');
const vacancy=action('a3_vacancy_tax'),mobilised=H.mobilisationPipeline(D,40,[vacancy]);ok(mobilised.activated>0&&mobilised.physicalNew===0,'Vacancy taxation mobilises existing homes without phantom construction');const icio=action('a3_supply_tax_cut');ok(H.mobilisationPipeline(D,4,[icio]).physicalNew===0&&H.mobilisationPipeline(D,40,[icio]).physicalNew>0,'ICIO relief produces delayed new housing rather than only price coefficients');
const tx=action('a3_transaction_tax_cut'),net=H.purchaseCost(D,4,[tx]);ok(net.factor<net.base&&net.foreignFactor===net.base,'First-home ITP/AJD relief reduces eligible resident purchase cost only');ok(measure(action('a3_anti_flip')).effects.filter(e=>e.target_id==='foreign_buyers').every(e=>e.amount<=0),'Anti-flip tax has no inherited foreign-buyer windfall');
const rehab=action('a3_empty_rehab',1,{units:1000,sale_pool:1e6}),rm=measure(rehab),ra=H.existingAt(rm,rehab,rm.existing_program.last_delivery_turn),rb=H.existingAt(rm,rehab,80);ok(rm.existing_program.affordability_required&&ra.rentalDelivered>rb.rentalDelivered,'Affordable rehabilitation is conditional and has an explicit retention period');
const rural=action('a3_rural_tax_zones'),shift=H.territorialShift(D,40,[rural],{},{}),share=D.rules.coherence.regional_origin_share;ok(shift.origin<0&&shift.destination>0&&Math.abs(shift.origin*share+shift.destination*(1-share))<1e-12,'Territorial relocation redistributes demand without adding national households');
// Feasible packages: default low-intensity measures, manual financing through the same UI routines.
let approved=0;for(const id of ['a3_freeze','a3_admin_staff','a3_training','a3_rent_aid_target','a3_migration_regularise']){
 const a=action(id,.02);E.ctx.index=a.index;E.run('openPolicy(index); draft.intensity=.02; draft.shares={};');
 E.run('for(const s of D.funding_sources){if(draft.funding.reduce((n,f)=>n+(f.share||0),0)>=100)break;const assigned=Object.values(draft.shares).reduce((n,v)=>n+v,0),share=Math.min(100-assigned,sourceMaxShare(s));if(share>0){draft.shares[s.id]=share;readFunding();}}');
 const errors=Array.from(E.run('validateDraft()'));assert.deepEqual(errors,[],id+' financed draft');const saved=clone(E.run('draft'));const v=E.at(4,[saved]);ok(v.every(Number.isFinite)&&v.diagnostics.coherence.finance,'Feasible financed package: '+id);approved++;
}
const invalid=clone(pack);invalid.model.measures.find(m=>m.supply_program?.private_capital_at_full!==undefined).supply_program.private_finance_share=1.1;ok(M.validate(invalid).length>0,'Private financing fractions are validated');const orphan=clone(pack);orphan.model.profiles=orphan.model.profiles.filter(p=>p.id!=='pensioners');ok(M.validate(orphan).length>0,'Deleting referenced profiles is rejected');assert.deepEqual(M.fromCatalog(D),pack);ok(true,'Editable new channels survive JSON roundtrip');
// All 67 measures at small, middle and stress intensity with sequential histories.
let scenarios=0;for(const m of D.measures)for(const intensity of [.02,.5,1]){const a=action(m.id,intensity);for(const t of [4,16,40,80]){const v=E.at(t,[a]);assert.ok(v.every(Number.isFinite),m.id+' finite');assert.ok(v.slice(0,6).every(n=>n>=0&&n<=100));scenarios++;}}
evidence.scenarios=scenarios;evidence.financed_packages=approved;fs.writeFileSync('/tmp/vivienda-coherence-verification.json',JSON.stringify(evidence,null,2));console.log('PASS: '+checks.length+' causal/accounting/financed/validation checks; '+scenarios+' isolated sensitivity scenarios; '+approved+' feasible financed packages.');
