const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),M=require('../assets/simulator/model-config'),H=require('../assets/simulator/housing-policy'),L=require('../assets/simulator/control-lab-core');
const pack=M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json'))),D=M.toCatalog(pack),i=D.measures.findIndex(m=>m.id==='a3_migration_remote_workers'),m=D.measures[i],a={index:i,start:1,intensity:1,annual_permits:0,income_threshold:60000,funding:[]};assert.ok(i>=0);assert.ok(!D.measures.some(m=>m.id==='a3_migration_reception'));assert.deepEqual(M.validate(pack),[]);
assert.equal(H.migrationCapacity(m,a),20000);assert.equal(H.migrationCapacity(m,{...a,annual_permits:20000}),0);assert.ok(H.migrationCapacity(m,{...a,income_threshold:150000})<20000);assert.equal(H.costs(m,{...a,annual_permits:20000}).initial,0);assert.equal(H.costs(m,{...a,annual_permits:20000}).quarter,0);
const p=H.migrationPipeline(D,12,[a]);assert.equal(p.departures,0);assert.equal(p.emigration_per_year,0);assert.ok(p.remote_workers>0&&p.remote_workers<=60000);assert.ok(p.gdp<0&&p.rent_demand<0&&p.buy_demand<0&&p.annual_tax_loss>0);assert.equal(H.migrationPipeline(D,1,[a]).remote_workers,0);assert.equal(H.migrationPipeline(D,80,[a]).remote_workers,p.remote_workers);assert.equal(H.migrationPipeline(D,80,[a]).immigration_per_year,0);
const broad={index:D.measures.findIndex(m=>m.id==='a3_migration_permits_limit'),start:1,intensity:1,funding:[]},alone=H.migrationPipeline(D,12,[broad]),combined=H.migrationPipeline(D,12,[a,broad]),reverse=H.migrationPipeline(D,12,[broad,a]);assert.ok(combined.remote_workers<p.remote_workers);assert.equal(combined.remote_workers,reverse.remote_workers);assert.ok(Math.abs(combined.immigration_per_year-alone.immigration_per_year)<1e-9,'Full general limits cover the remote subgroup after ramp');
for(const extra of [{annual_permits:-1},{annual_permits:20001},{annual_permits:101},{income_threshold:59000},{income_threshold:NaN}])assert.ok(H.migrationConflicts(D,[{...a,...extra}]).length);
const ctr=L.controls(D,i,a);assert.deepEqual(ctr.map(c=>c.key),['annual_permits','income_threshold']);const adjusted=L.adjust(D,i,a,ctr[0],10000);assert.equal(adjusted.annual_permits,10000);assert.equal(adjusted.intensity,.5);assert.ok(H.migrationCapacity(m,L.adjust(D,i,adjusted,ctr[1],150000))<H.migrationCapacity(m,adjusted));
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{querySelector(){return null;},style:{setProperty(){}},dataset:{},setAttribute(){},showModal(){},close(){}});return nodes.get(id);},ctx=vm.createContext({window:{SIM_CATALOG:D,SIM_MODEL:M},Intl,structuredClone,document:{getElementById:node,querySelector:node}});for(const f of ['housing-policy','national','public-debt','fiscal','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),ctx);ctx.actions=[a];const baseline=vm.runInContext('outcome(12,[])',ctx),restricted=vm.runInContext('outcome(12,actions)',ctx);assert.ok(restricted[10]<baseline[10]);assert.ok(restricted[12]<baseline[12]);assert.ok(restricted[11]<baseline[11]);assert.equal(restricted.diagnostics.availableHomes,baseline.diagnostics.availableHomes);assert.ok(restricted[6]<baseline[6]);assert.ok(restricted[7]<baseline[7]);assert.ok(restricted[9]<baseline[9]);vm.runInContext('openPolicy('+i+')',ctx);assert.equal(node('intensity-label').textContent,'Nuevas autorizaciones permitidas al año');assert.equal(node('remote-worker-controls').hidden,false);
// An edited old measure must not be resurrected in an existing internal draft.
const old=M.clone(pack);old.metadata.version='old';old.model.measures[i]={...m,id:'a3_migration_reception',name:'Old reception'};const mine=M.clone(old);mine.model.measures[i].name='Edited old reception';mine.comments=[{id:'keep',anchor:{section:'measures',entity_id:'a3_migration_reception',field:[]},text:'Historic note',status:'pending'}];const merged=L.update(old,mine,pack).pack;assert.ok(!merged.model.measures.some(m=>m.id==='a3_migration_reception'));assert.ok(merged.model.measures.some(m=>m.id==='a3_migration_remote_workers'));assert.equal(merged.comments[0].text,'Historic note');
console.log('PASS: quota and income threshold, no expulsions or phantom homes, finite entry cohorts, general-permit overlap, consumption/GDP and differentiated rent/buy demand, validation, game controls, panel controls and old-draft replacement.');
