const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../assets/simulator/model-config.js');
const c=JSON.parse(fs.readFileSync('data/simulator/catalog.json','utf8')),p=M.fromCatalog(c),clone=M.clone;
assert.deepEqual(M.validate(p),[]);
assert.deepEqual(M.fromCatalog(c),p,'Seed generation is deterministic');
p.comments.push({id:'comment_test',anchor:{section:'measures',entity_id:p.model.measures[0].id,field:['effects','amount'],effect_id:p.model.measures[0].effects[0].id},text:'Verificar este efecto con evidencia española.',status:'pending',created_at:'2026-10-03T12:00:00Z',updated_at:'2026-10-03T12:00:00Z'});
p.extension_for_review={notes:['Unknown fields survive export and reimport.']};
assert.deepEqual(JSON.parse(JSON.stringify(p)),p,'Lossless roundtrip includes comments and extension fields');
assert.deepEqual(M.validate(p),[]);
const before=clone(p);p.model.measures.reverse();p.model.measures.find(m=>m.id===p.comments[0].anchor.entity_id).effects.reverse();
assert.ok(p.model.measures.find(m=>m.id===p.comments[0].anchor.entity_id).effects.some(e=>e.id===p.comments[0].anchor.effect_id),'Comment anchors survive reordering by stable IDs');
assert.ok(M.diff(before,p).some(d=>d.path.endsWith('$order')));
function invalid(change,pattern){const x=clone(before);change(x);assert.ok(M.validate(x).some(e=>pattern.test(e.path+' '+e.message)),pattern.toString());}
invalid(x=>x.model.measures.push(clone(x.model.measures[0])),/duplicado/);
invalid(x=>x.model.measures[0].effects[0].target_id='missing',/huérfano/);
invalid(x=>x.model.measures[0].intensity_max=-1,/intensity_max/);
invalid(x=>x.model.groups[0].weight=10,/sumar 100/);
invalid(x=>x.model.measures[0].sources=['missing'],/Referencia inexistente/);
invalid(x=>x.model.measures[0].regulation_sources=['missing'],/regulation_sources/);
invalid(x=>{x.model.measures[0].dependencies=[x.model.measures[1].id];x.model.measures[1].dependencies=[x.model.measures[0].id];},/circulares/);
invalid(x=>x.model.variables=x.model.variables.filter(v=>v.id!=='gdp'),/Falta variable/);
invalid(x=>x.model.territories[0].population_share=95,/cuotas territoriales/);
invalid(x=>x.model.sources[0].url='javascript:alert(1)',/HTTP/);
invalid(x=>x.model.measures[0].effects[0].duration_turns=0,/duration_turns/);
invalid(x=>x.model.measures[0].effects[0].requires=['missing'],/Referencia inexistente/);
invalid(x=>x.model.funding_sources[0].response=0,/response/);
invalid(x=>x.model.groups[0]=null,/incompleta|válido/);
invalid(x=>x.schema_version=99,/compatible/);
invalid(x=>x.comments.push(clone(x.comments[0])),/comentario duplicados/);
const polluted=JSON.parse(JSON.stringify(before).replace('"schema_version":1','"schema_version":1,"__proto__":{"x":1}'));
assert.ok(M.validate(polluted).some(e=>/Clave/.test(e.message)));
function engine(pack){const catalog=M.toCatalog(pack),nodes=new Map(),ctx=vm.createContext({window:{SIM_CATALOG:catalog,SIM_MODEL:M},document:{getElementById(id){if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);}},Intl,structuredClone});for(const file of ['housing-policy.js','national.js','fiscal.js','advanced.js'])vm.runInContext(fs.readFileSync('assets/simulator/'+file,'utf8'),ctx);return {ctx,catalog,run:expr=>vm.runInContext(expr,ctx)};}
const {run,catalog}=engine(before);
const pension=catalog.funding_sources.find(s=>s.id==='a3_cut_pensions');
const transfer=catalog.funding_sources.find(s=>s.id==='a3_tax_itp');
assert.ok(pension.group_effects.resident_owners<pension.group_effects.tenants,'Pension cuts follow estimated pensioner exposure by tenure');
assert.equal(pension.group_effects.foreign_buyers,0,'Non-resident buyers do not receive Spanish pensions in the model');
assert.ok(transfer.group_effects.domestic_buyers<transfer.group_effects.tenants,'Transfer tax concentrates on buyers');
assert.equal(run('outcome(80,[]).length'),9+catalog.national.indicators.length);
assert.ok(run('outcome(80,[]).every(Number.isFinite)'));
for(let i=0;i<catalog.measures.length;i++){
 const value=run(`outcome(80,[{index:${i},start:1,intensity:1,funding:[]}])`);
 assert.ok(value.every(Number.isFinite),catalog.measures[i].id);
}
const extended=clone(before);
extended.model.variables.push({id:'construction_workers',name:'Trabajadores de construcción',unit:'personas',initial:100,visible:true,min:0,max:1000,annual_growth:.1,sources:[],status:'Hipótesis',definition:'Prueba de extensión'});
extended.model.groups.push({id:'young_households',name:'Hogares jóvenes',engine_slot:'',initial:40,weight:10,collective_sensitivity:1,visible:true,min:0,max:100,note:'Grupo de prueba',sources:[],funding_exposure:{...extended.model.groups.find(g=>g.id==='tenants').funding_exposure,pension:.02}});
extended.model.groups.find(g=>g.id==='resident_owners').weight-=10;
const measure=clone(extended.model.measures[0]);delete measure.price_control;measure.id='test_policy';measure.name='Política de prueba';measure.risk_high=false;measure.dependencies=[];measure.initial_cost=0;measure.quarterly_cost=0;
measure.effects=[{id:'jobs',target_type:'variable',target_id:'construction_workers',amount:20,operation:'absolute',delay_turns:2,maturation_turns:0,duration_turns:8,permanent:false,min_value:0,max_value:125,requires:[]},{id:'happiness',target_type:'group',target_id:'young_households',amount:10,operation:'points',delay_turns:0,maturation_turns:0,duration_turns:8,permanent:false,min_value:0,max_value:100,requires:[]}];
extended.model.measures=[measure];M.syncFundingEffects(extended);assert.deepEqual(M.validate(extended),[]);
const ex=engine(extended),customIndex=9+catalog.national.indicators.length;
assert.equal(ex.run('initialState().extraGroups.young_households'),40);
assert.ok(ex.run('outcome(1,[{index:0,start:1,intensity:1,funding:[]}]).extraGroups.young_households')>40);
assert.equal(ex.run(`outcome(1,[{index:0,start:1,intensity:1,funding:[]}])[${customIndex}]`),100*Math.pow(1.1,.25),'Deferred custom effect has not started');
assert.equal(ex.run(`outcome(3,[{index:0,start:1,intensity:1,funding:[]}])[${customIndex}]`),125,'Custom effect is applied and bounded');
assert.ok(ex.run(`outcome(10,[{index:0,start:1,intensity:1,funding:[]}])[${customIndex}]`)>125,'Expired bound and effect no longer apply');
assert.equal(M.policyAt(ex.catalog,ex.catalog.measures[0],{index:0,start:1,intensity:1,funding:[]},9,[]).groups.young_households||0,0,'Temporary group effect expires; macro income can continue to affect satisfaction');
extended.model.measures[0].enabled=false;assert.equal(engine(extended).catalog.measures.length,0,'Disabled measures do not reach the game');
const funding=clone(before);funding.model.groups[0].funding_exposure.pension=2;assert.ok(M.validate(funding).some(e=>/funding_exposure.pension/.test(e.path)));
const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};
let state=M.readStore(storage);state=M.writeStore(storage,{...state,draft:before},0);assert.equal(state.revision,1);assert.equal(state.active,null,'Saving draft does not publish');
assert.throws(()=>M.writeStore(storage,state,0),/Otra pestaña/,'Concurrent write prevented');
state=M.writeStore(storage,{...state,active:before,previous:p},1);assert.deepEqual(M.readStore(storage).active,before);state=M.writeStore(storage,{...state,active:state.previous,previous:state.active},2);assert.deepEqual(state.active,p,'Previous version can be restored');
const snapshot=engine(before);const original=snapshot.run('initialState()[6]');const later=clone(before);later.model.prices.rent.value=99;engine(later);assert.equal(snapshot.run('initialState()[6]'),original,'Existing games retain snapshot');
console.log('PASS: JSON roundtrip/extensions/comments, stable anchors, 16 invalid-config cases, all measures through 80 turns, new group and variable without code edits, deferred/instant/bounded effects, expiry, disable, drafts/publication/restore, conflict protection and immutable game snapshots.');
