const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),debt=require('../assets/simulator/public-debt'),M=require('../assets/simulator/model-config');
const terms={annual_rate:.04,reduction_delay_turns:1,repayment_turns:80},a={start:1},draw=t=>t===1?1000:t===2?200:0;
assert.deepEqual(debt.at(a,0,draw,terms),{balance:0,draw:0,interest:0,principal:0,reduction:0});
assert.deepEqual(debt.at(a,1,draw,terms),{balance:1000,draw:1000,interest:0,principal:0,reduction:0});
assert.deepEqual(debt.at(a,2,draw,terms),{balance:1187.5,draw:200,interest:10,principal:12.5,reduction:22.5});
assert.equal(debt.at(a,3,draw,terms).principal,15);assert.equal(debt.at(a,3,draw,terms).interest,11.875);
assert.equal(debt.at(a,82,draw,terms).balance,0);assert.equal(debt.at(a,83,draw,terms).reduction,0);
let repaid=0;for(let t=1;t<=82;t++)repaid+=debt.at(a,t,draw,terms).principal;assert.equal(repaid,1200);
const sources=[{id:'pensions',kind:'spending_cut',annual_reference:200},{id:'unemployment',kind:'spending_cut',annual_reference:25},{id:'debt',kind:'spending_cut',annual_reference:10,debt_service:true}];
assert.deepEqual(debt.allocate(90,['pensions','unemployment'],sources),{pensions:80,unemployment:10});assert.throws(()=>debt.allocate(10,['debt'],sources));assert.deepEqual(debt.allocate(100,['pensions','unemployment'],sources,{pensions:30,unemployment:70}),{pensions:30,unemployment:70});assert.throws(()=>debt.allocate(10,['pensions'],sources,{pensions:-1}));
const D=M.toCatalog(M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json')))),nodes=new Map(),ctx=vm.createContext({window:{SIM_CATALOG:D,SIM_MODEL:M},Intl,structuredClone,document:{getElementById(id){if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);}}});
for(const f of ['housing-policy','national','public-debt','fiscal','turn-report','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
run("years=20;turn=0;draft={index:D.measures.findIndex(m=>m.id==='a3_public_build'),intensity:.1,start:1,shares:{a3_public_debt:100},funding:[],debt:{source_ids:['a3_cut_health'],terms:D.rules.public_debt}};readFunding(); active=[structuredClone(draft)]");
assert.equal(run('debtTotals(1,active).reduction'),0);assert.ok(Math.abs(run('aggregate(outcome(1,active))-aggregate(outcome(1,[{...active[0],funding:[],debt:undefined}]))'))<1e-9,'Issuing debt alone has no immediate direct social effect');assert.ok(run('aggregate(outcome(2,active))>aggregate(outcome(2,[{...active[0],funding:[],debt:undefined}]))'),'Repayment budget cuts lower happiness from the following quarter');
assert.ok(run('debtTotals(2,active).interest>0&&debtTotals(2,active).principal>0'));
for(const t of [1,2,16,40,80,160])assert.ok(Math.abs(run(`fiscalBalance({},${t},active)`))<.02,'Borrowing, programme costs and repayments balance at '+t);
assert.equal(run("amountFor(active[0],D.funding_sources.find(s=>s.id==='a3_cut_health'),2)"),run('debtTotals(2,active).reduction'));
assert.ok(run('outcome(12,active).every(Number.isFinite)'));assert.ok(run("debtReport(40,active).includes('Principal pendiente')"));
run("active[0].debt.source_ids=['a3_cut_health','a3_cut_education'];active[0].debt.source_shares={a3_cut_health:30,a3_cut_education:70}");assert.ok(Math.abs(run("amountFor(active[0],D.funding_sources.find(s=>s.id==='a3_cut_health'),2)")/run('debtTotals(2,active).reduction')-.3)<1e-9);assert.ok(Math.abs(run('fiscalBalance({},2,active)'))<.02);run('active[0].cancelled_turn=3');assert.ok(run('debtTotals(8,active).principal>0'),'Cancellation cannot erase outstanding debt');
console.log('PASS: quarterly principal/interest, proportional reductions, full repayment, balanced fiscal accounting, finite outcomes and debt retained after cancellation.');
