const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{style:{},setAttribute(k,v){this[k]=v;}});return nodes.get(id);};
const ctx=vm.createContext({window:{SIM_CATALOG:JSON.parse(fs.readFileSync('data/simulator/catalog.json')),SIM_MODEL:require('../assets/simulator/model-config')},document:{getElementById:node},Intl,structuredClone});
for(const f of ['housing-policy','national','fiscal','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),ctx);
const angle=(ads,seekers)=>vm.runInContext(`listingBalanceAngle(${ads},${seekers})`,ctx);
const values=[.1,.25,.5,.75,1,1.25,1.5,2,4,10].map(r=>angle(100,100*r));
assert.equal(new Set(values).size,10,'More than seven distinct inclinations');
assert.ok(values.every((a,i)=>!i||a>values[i-1]),'More demand lowers the demand pan continuously');
assert.equal(angle(100,100),0);assert.equal(angle(0,0),0);
assert.ok(angle(0,100)>0);assert.ok(angle(100,0)<0);
assert.ok(Math.abs(angle(100,200)+angle(200,100))<1e-10,'Supply/demand symmetry');
vm.runInContext('history=[initialState()];turn=0;renderListings()',ctx);
assert.ok(node('rent-seekers').textContent);assert.ok(node('sale-seekers').textContent);
const old=node('rent-balance-beam').style.transform;
vm.runInContext('history[0][9+nationalKeys.indexOf("rent_demand")]*=2;renderListings()',ctx);
assert.notEqual(node('rent-balance-beam').style.transform,old,'Uses live national demand');
assert.ok(!node('rent-balance-pan-left').style.transform.includes('NaN'));
vm.runInContext('renderNational()',ctx);
assert.equal((node('national-grid').innerHTML.match(/<article /g)||[]).length,4,'Four national cards remain');
assert.ok(!node('national-grid').innerHTML.includes('data-info="national:rent_demand"'));
assert.ok(!node('national-grid').innerHTML.includes('data-info="national:buy_demand"'));
console.log('PASS: continuous inclination, ten distinct positions, equilibrium, symmetry, empty markets and live data rendering.');
