const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),M=require('../assets/simulator/model-config'),H=require('../assets/simulator/housing-policy');
const pack=M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json'))),D=M.toCatalog(pack),by=id=>D.measures.find(m=>m.id===id),idx=id=>D.measures.findIndex(m=>m.id===id);
assert.deepEqual(M.validate(pack),[]);for(const id of ['a3_energy_rehab','a3_accessibility','a3_sareb'])assert.equal(by(id),undefined);
const purchase=by('a3_buy_existing'),rehab=by('a3_empty_rehab'),a={index:idx(purchase.id),start:1,intensity:.001,units:1000,sale_pool:10000,purchase_price:2355,rent_reference:8.2,funding:[]};
assert.equal(H.costs(purchase,a).initial,198820000);assert.equal(H.costs(purchase,a).quarter,500000);assert.equal(H.existingAt(purchase,a,1).delivered,0);assert.equal(H.existingAt(purchase,a,4).delivered,1000);assert.equal(H.existingAt(purchase,a,80).delivered,1000);
assert.ok(H.costs(purchase,{...a,purchase_price:3000}).initial>H.costs(purchase,a).initial);assert.equal(H.costs(rehab,{...a,index:idx(rehab.id)},2).initial,62000000);
assert.equal(H.existingConflicts(D.measures,[{...a,units:5000}]).length,0);assert.ok(H.existingConflicts(D.measures,[{...a,units:5001}]).length);assert.equal(H.existingConflicts(D.measures,[{...a,index:idx(rehab.id),units:2000}]).length,0);assert.ok(H.existingConflicts(D.measures,[{...a,index:idx(rehab.id),units:2001}]).length);
assert.equal(H.existingAt(rehab,{...a,index:idx(rehab.id)},3).delivered,0);assert.equal(H.existingAt(rehab,{...a,index:idx(rehab.id)},8).delivered,850);
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{style:{setProperty(){}},dataset:{},setAttribute(){},showModal(){},labels:[{}],querySelectorAll(){return[]},insertAdjacentHTML(){},focus(){}});return nodes.get(id);},ctx=vm.createContext({window:{SIM_CATALOG:D,SIM_MODEL:M},Intl,structuredClone,document:{getElementById:node,querySelector:()=>node('methodology')}});for(const f of ['housing-policy','national','fiscal','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),ctx);ctx.a=a;const run=s=>vm.runInContext(s,ctx);
assert.equal(run('outcome(8,[a])[15]'),run('outcome(8,[])[15]'),'Purchase creates no new physical stock');assert.ok(run('listingValues(outcome(1,[a])).sale')<run('listingValues(outcome(1,[])).sale'));assert.ok(run('listingValues(outcome(4,[a])).rent')>run('listingValues(outcome(4,[])).rent'));assert.equal(H.existingPipeline(D,8,[a]).publicHomes,1000);assert.ok(Math.abs(H.existingPipeline(D,8,[a]).annualRentIncome-5608800)<.01);assert.ok(M.policyAt(D,purchase,{...a,units:1,intensity:.000001},4,[a]).groups.tenants>0,'Small selections still have a proportional effect');
run('renderFunding=()=>{};history=[initialState()]');run(`openPolicy(${idx(purchase.id)})`);assert.equal(+node('intensity').max,run('Math.floor(listingValues(initialState()).sale*.5)'));assert.equal(+node('intensity').step,1);assert.ok(node('maintenance').textContent.includes('540'));node('intensity').oninput({target:{value:'123'}});assert.equal(run('draft.units'),123);assert.equal(+node('intensity').value,123);
run(`openPolicy(${idx(rehab.id)})`);assert.equal(+node('intensity').max,run('Math.floor(listingValues(initialState()).sale*.2)'));
for(const id of ['a3_sale_resale_cap','a3_sale_cost_cap','a3_sale_general_cap']){const m=by(id),act={index:idx(id),start:1,intensity:1,enforcement:1,funding:[]};assert.ok(M.policyAt(D,m,act,8,[act]).price.sale<0);assert.equal(M.policyAt(D,m,act,41,[act]).price.sale,0);assert.equal(H.costs(m,{...act,enforcement:0}).quarter,0);ctx.capAction=act;assert.equal(run('outcome(8,[capAction]).rentalWithdrawal'),0,'Sale control must not withdraw rental ads');assert.ok(run('outcome(8,[capAction]).saleWithdrawal')>0);}
const bad=M.clone(pack);bad.model.measures.find(m=>m.existing_program).existing_program.max_sale_share=2;assert.ok(M.validate(bad).length);
assert.deepEqual(M.fromCatalog(D),pack);console.log('PASS: current-price acquisition costs, market-linked quantity sliders, 50/20% bounds, no phantom construction, delayed rental transfers, small selections, sale/rent withdrawals separated, expiry, validation and roundtrip.');
