/* Behavioral regression: timing, opt-out, offline queue and duplicate-safe retry. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
async function fixture(){let now=0,status='offline',seq=0;const values=new Map(),handlers={},posted=new Map();const doc={hidden:false,hasFocus:()=>true,getElementById:()=>({append(){}}),querySelector:()=>({append(){}}),createElement:()=>({querySelector:()=>({}),set innerHTML(v){}}),addEventListener:(name,fn)=>{(handlers[name]??=[]).push(fn);}};
const localStorage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k),key:i=>[...values.keys()][i],get length(){return values.size;}};
const context={window:{SIM_SUPABASE:{url:'https://example.test',publishableKey:'public'}},document:doc,localStorage,performance:{now:()=>now},crypto:{randomUUID:()=>`00000000-0000-4000-8000-${String(++seq).padStart(12,'0')}`},structuredClone,AbortController,queueMicrotask,setTimeout,clearTimeout,setInterval(){},fetch:async(url,opts)=>{if(url.includes('settings'))return {ok:true,json:async()=>[{enabled:true,idle_seconds:90}]};if(status==='offline')throw new Error('offline');const rows=JSON.parse(opts.body);if(rows.some(e=>posted.has(e.id)))return {ok:false,status:409,json:async()=>({code:'23505'})};for(const e of rows)posted.set(e.id,e);return {ok:true};}};
context.window.addEventListener=doc.addEventListener;vm.runInNewContext(fs.readFileSync('assets/simulator/decision-tracking.js','utf8'),context);await new Promise(setImmediate);
return {api:context.window.SIM_TRACKING,values,posted,time(n){now=n*1000;},fire(name,target={}){for(const fn of handlers[name]||[])fn({target});},doc,online(){status='online';},logs(){return JSON.parse(values.get('vivienda.tracking.local-events'));},async settle(){for(let i=0;i<5;i++)await new Promise(setImmediate);}};}
(async()=>{const f=await fixture();f.api.start('test',10);f.api.open('measure-a',{intensity:.5,funding:[]});f.time(120);f.api.checkpoint();let e=f.logs().at(-1);assert.equal(e.active_seconds,90);assert.equal(e.visible_seconds,120);assert.equal(e.measure_active_seconds,90);f.fire('pointerdown');f.api.draft({intensity:.75,funding:[]},['Not funded']);f.fire('change');f.time(140);f.api.checkpoint();e=f.logs().at(-1);assert.equal(e.active_seconds,110);assert.equal(e.data.measure_consultation_seconds,90);assert.equal(e.data.measure_configuration_seconds,20);f.doc.hidden=true;f.fire('visibilitychange');f.time(180);f.api.checkpoint();assert.equal(f.logs().at(-1).active_seconds,110);f.doc.hidden=false;f.fire('visibilitychange');f.time(190);f.api.close();e=f.logs().at(-1);assert.equal(e.active_seconds,120);assert.equal(e.measure_active_seconds,120);assert.equal(e.data.visit_active_seconds,120);
assert.ok([...f.values.keys()].some(k=>k.startsWith('vivienda.tracking.queue.')),'Offline queue persists');const pending=JSON.parse([...f.values].find(([k])=>k.startsWith('vivienda.tracking.queue.'))[1]);f.posted.set(pending[0].id,pending[0]);await f.settle();f.online();f.fire('online');await f.settle();assert.equal(f.posted.size,pending.length);assert.ok(![...f.values.keys()].some(k=>k.startsWith('vivienda.tracking.queue.')),'Duplicate retry drains without loss');const id=f.logs()[0].game_id;f.api.start('test',10);assert.notEqual(f.api.gameId,id);f.api.commit(1,[{measure_id:'measure-b',intensity:.5}],true);assert.equal(f.api.gameId,null);assert.ok(f.logs().some(e=>e.event_type==='game_completed'));assert.equal(f.logs().find(e=>e.event_type==='measure_applied').turn,1);console.log('PASS: 90-second idle cutoff, consultation/configuration time, hidden-tab pause, close snapshot, durable offline queue, duplicate-safe retry, new game identity and completed turn events.');})().catch(e=>{console.error(e);process.exitCode=1;});
