const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),M=require('../assets/simulator/model-config'),H=require('../assets/simulator/housing-policy');
const pack=M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json'))),D=M.toCatalog(pack),by=id=>D.measures.find(m=>m.id===id),idx=id=>D.measures.findIndex(m=>m.id===id),act=(id,intensity=1)=>({index:idx(id),start:1,intensity,funding:[],shares:{}});
assert.deepEqual(M.validate(pack),[]);assert.equal(D.measures.filter(m=>m.category==='access').length,8);assert.deepEqual(M.fromCatalog(D),pack);
for(const m of D.measures.filter(m=>m.category==='access')){assert.ok(m.selection_description.split(/[.!?]\s/).length>=3);assert.ok(m.access_program.reference_note);assert.ok(m.access_program.range_note);if(!m.temporal_control){const small=H.costs(m,act(m.id,.001)),full=H.costs(m,act(m.id));assert.ok(small.initial+small.quarter<full.initial+full.quarter);assert.ok(m.quantity_control);}}
const target=by('a3_rent_aid_target'),t=act(target.id);assert.equal(H.costs(target,t).initial,176326000);assert.equal(H.costs(target,t).quarter,175000000);assert.equal(H.accessAt(target,t,3),0);assert.equal(Math.round(H.accessAt(target,t,5)),115000);assert.equal(M.policyAt(D,target,t,3,[t]).price.rent,0);assert.equal(M.policyAt(D,target,t,5,[t]).price.rent,0,'Rent pressure is derived from actual demand, not a duplicated price coefficient');assert.ok(M.policyAt(D,target,t,5,[t]).variables.rent_demand.percent>0);
const hf=by('a3_housing_first'),h=act(hf.id),eff=M.policyAt(D,hf,h,4,[h]);assert.ok(eff.variables.rent_demand.percent>0);assert.equal(eff.variables.available_homes,undefined);
const guarantee=by('a3_mortgage_guarantee'),g={...act(guarantee.id),purchase_price:2355},gc=H.costs(guarantee,g);assert.equal(gc.exposure,3768000000);assert.equal(gc.initial,238400000);assert.ok(gc.initial<gc.exposure);assert.ok(H.costs(guarantee,{...g,purchase_price:3000}).initial>gc.initial);assert.equal(M.policyAt(D,guarantee,g,4,[g]).price.sale,0);assert.ok(M.policyAt(D,guarantee,g,4,[g]).variables.buy_demand.percent>0);
const relief=act('a3_mortgage_relief');assert.equal(H.costs(by('a3_mortgage_relief'),relief).fiscalQuarter,225000000);assert.ok(H.fiscalConflicts(D.measures,[relief,{...h,funding:[{source_id:'a3_tax_irpf',initial_amount:0,quarterly_amount:100000}]}]).length);assert.equal(H.fiscalConflicts(D.measures,[relief,{...h,funding:[{source_id:'a3_tax_iva',initial_amount:0,quarterly_amount:100000}]}]).length,0);
const sale={...act('a3_tenant_purchase'),management:4};assert.equal(H.publicStockAt(D,4,[sale]).stock,190000);assert.equal(H.publicStockAt(D,80,[sale]).stock,190000);assert.equal(H.publicStockAt(D,1,[sale]).available,190000);assert.ok(H.accessConflicts(D,[sale,{...sale,start:9},{...sale,start:17}]).length);assert.equal(M.policyAt(D,by('a3_tenant_purchase'),sale,10,[sale]).price.sale,0);assert.equal(M.policyAt(D,by('a3_tenant_purchase'),sale,80,[sale]).price.rent,0,'Public-stock loss is endogenous');
const moratorium=by('a3_eviction_moratorium'),one={...act(moratorium.id),duration_turns:1},long={...one,duration_turns:12},cancel={...long,cancelled_turn:3};assert.equal(H.actionEnd(moratorium,one),2);assert.ok(M.policyAt(D,moratorium,one,1,[one]).groups.tenants>0);assert.deepEqual(M.policyAt(D,moratorium,one,2,[one]).groups,{});assert.equal(M.policyAt(D,moratorium,long,12,[long]).price.rent,0);assert.equal(M.policyAt(D,moratorium,long,13,[long]).price.rent,0);assert.equal(M.policyAt(D,moratorium,cancel,2,[cancel]).price.rent,0);assert.equal(M.policyAt(D,moratorium,cancel,3,[cancel]).price.rent,0);assert.ok(H.accessConflicts(D,[{...long,duration_turns:13}]).length);
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{style:{setProperty(){}},dataset:{},setAttribute(){},showModal(){},labels:[{}],querySelectorAll(){return[]},insertAdjacentHTML(){},focus(){}});return nodes.get(id);},ctx=vm.createContext({window:{SIM_CATALOG:D,SIM_MODEL:M},Intl,structuredClone,document:{getElementById:node,querySelector:()=>node('methodology')}});for(const f of ['housing-policy','national','fiscal','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),ctx);const run=s=>vm.runInContext(s,ctx);ctx.one=one;ctx.long=long;ctx.cancel=cancel;ctx.sale=sale;
assert.ok(run('fiscalCost(1,[one])')>0);assert.equal(run('fiscalCost(2,[one])'),0);assert.equal(run('fiscalCost(3,[cancel])'),0);assert.ok(run('fiscalCost(2,[cancel])')>0);assert.equal(run('outcome(3,[cancel]).rentalWithdrawal'),0);assert.ok(run('outcome(2,[cancel]).rentalWithdrawal')>0);assert.equal(run('outcome(80,[sale])[15]'),run('outcome(80,[])[15]'),'Sale adds no physical housing');
run('renderFunding=()=>{};history=[initialState()]');run(`openPolicy(${idx(moratorium.id)})`);assert.equal(+node('intensity').min,1);assert.equal(+node('intensity').max,12);assert.equal(+node('intensity').value,4);node('intensity').oninput({target:{value:'1'}});assert.equal(run('draft.duration_turns'),1);assert.equal(run('draft.intensity'),1);assert.ok(node('quantity-preview').textContent.includes('2027'));assert.equal(node('cost-total').textContent,run('money(costs(D.measures[draft.index],1,1,draft).initial+costs(D.measures[draft.index],1,1,draft).quarter)'));
run('active=[{...long}];turn=1;history=[initialState(),outcome(1,active)];render=()=>{}');run('cancelActivePolicy(0)');assert.equal(run('active[0].cancelled_turn'),2);assert.equal(run('active.length'),1);assert.equal(run('history.length'),2);assert.equal(run('fiscalCost(2,active)'),0);
assert.equal(H.durationLabel(1),'3 meses');assert.equal(H.durationLabel(5),'1 año y 3 meses');assert.equal(H.durationLabel(12),'3 años');
assert.ok(M.policyAt(D,moratorium,long,1,[long]).groups.tenants>M.policyAt(D,moratorium,one,1,[one]).groups.tenants);
assert.ok(M.policyAt(D,moratorium,long,1,[long]).groups.landlords<M.policyAt(D,moratorium,one,1,[one]).groups.landlords);
for(const m of D.measures.filter(m=>m.access_program)){const base=act(m.id),poor={...base,management:0},rich={...base,management:4};assert.ok(H.costs(m,rich).initial+H.costs(m,rich).quarter>H.costs(m,poor).initial+H.costs(m,poor).quarter);assert.ok(H.accessAt(m,rich,8)>H.accessAt(m,poor,8));assert.ok(H.accessConflicts(D,[{...base,management:5}]).length);}
run('active=[];turn=0;history=[initialState()]');run(`openPolicy(${idx(target.id)})`);assert.equal(node('enforcement-label').textContent,'Medios de gestión y seguimiento');run('draft.intensity=1');node('enforcement').oninput({target:{value:'4'}});assert.equal(run('draft.management'),4);assert.ok(node('enforcement-capacity').textContent.includes('200.000'));run(`openPolicy(${idx(moratorium.id)})`);node('intensity').oninput({target:{value:'5'}});assert.equal(node('intensity-value').textContent,'1 año y 3 meses');
const bad=M.clone(pack);bad.model.measures.find(m=>m.temporal_control).temporal_control.max_turns=13;assert.ok(M.validate(bad).length);console.log('PASS: audited administration costs, delayed aid, scalable beneficiaries, housing demand without new stock, contingent guarantees, IRPF lock, finite permanent public-stock loss, 1–12 quarter expiry, future-only cancellation, funding and UI duration control.');
