const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),M=require('../assets/simulator/model-config'),H=require('../assets/simulator/housing-policy');
const pack=M.fromCatalog(JSON.parse(fs.readFileSync('data/simulator/catalog.json'))),D=M.toCatalog(pack),nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{style:{setProperty(){}},dataset:{},setAttribute(){},showModal(){},close(){}});return nodes.get(id)},ctx=vm.createContext({window:{SIM_CATALOG:D,SIM_MODEL:M},Intl,structuredClone,document:{getElementById:node,querySelector:node}});
for(const f of ['housing-policy','national','fiscal','advanced'])vm.runInContext(fs.readFileSync('assets/simulator/'+f+'.js','utf8'),ctx);const run=s=>vm.runInContext(s,ctx),values=Object.fromEntries(D.display_groups.map(g=>[g.id,g.initial])),b=D.national.baseline;
assert.deepEqual(M.validate(pack),[]);assert.ok(Math.abs(D.display_groups.reduce((n,g)=>n+g.weight,0)-100)<1e-9);assert.equal(D.display_groups.filter(g=>g.weight>0).length,6);assert.equal(D.display_groups.find(g=>g.id==='foreign_buyers').weight,0);
const plain=H.collectiveHappiness(D,values,b.gdp,b.population,1,{},null),excluded=H.collectiveHappiness(D,{...values,foreign_buyers:0},b.gdp,b.population,1,{},null);assert.equal(plain.finalIndex,excluded.finalIndex,'Foreign investors never change the collective mean');
for(const g of D.display_groups.filter(g=>g.weight>0)){const moved=H.collectiveHappiness(D,{...values,[g.id]:values[g.id]-10},b.gdp,b.population,1,{},null);assert.ok(moved.finalIndex<plain.finalIndex,g.id+' contributes positively to index');}
const pension=D.funding_sources.find(s=>s.id==='a3_cut_pensions'),health=D.funding_sources.find(s=>s.id==='a3_cut_health');const stress=H.collectiveHappiness(D,values,b.gdp,b.population,1,{[pension.id]:pension.annual_reference/4},null),small=H.collectiveHappiness(D,values,b.gdp,b.population,1,{[pension.id]:pension.annual_reference*.01/4},null);
assert.ok(plain.finalIndex-stress.finalIndex>40,'Complete pension abolition provokes severe shared rejection, even holding GDP and own income constant');assert.ok(plain.finalIndex-small.finalIndex<1,'Small adjustments are distinct from dismantling a whole programme');
const healthLoss=H.collectiveHappiness(D,values,b.gdp,b.population,1,{[health.id]:health.annual_reference*.2/4},null);assert.ok(healthLoss.finalIndex<plain.finalIndex,'Healthcare cuts affect collective mood beyond direct users');
const tax=D.funding_sources.find(s=>s.id==='a3_tax_irpf'),up=H.collectiveHappiness(D,values,b.gdp,b.population,1,{[tax.id]:tax.annual_reference*.3/4},null),down=H.collectiveHappiness(D,values,b.gdp,b.population,1,{[tax.id]:-tax.annual_reference*.3/4},null);assert.ok(up.finalIndex<plain.finalIndex&&down.finalIndex>plain.finalIndex,'Taxes affect shared mood in both directions');
const recession=H.collectiveHappiness(D,values,b.gdp*.9,b.population,1,{},null);assert.ok(plain.finalIndex-recession.finalIndex>20,'A real GDP recession has a substantial social consequence');assert.equal(recession.final.tenants,Math.max(0,values.tenants+recession.shared),'Rebound follows group sensitivity');
const noFeedback=M.clone(D);noFeedback.display_groups.find(g=>g.id==='resident_owners').collective_sensitivity=0;assert.equal(H.collectiveHappiness(noFeedback,values,b.gdp*.9,b.population,1,{},null).final.resident_owners,values.resident_owners,'Zero sensitivity removes only shared rebound');
const ref={diagnostics:{collective:{directIndex:plain.directIndex,macro:0}}};for(const [i,k]of D.national.indicators.entries())ref[9+i]=b[k.key];const shock=H.collectiveHappiness(D,{...values,resident_owners:40},b.gdp,b.population,1,{},ref);assert.ok(shock.peer<0&&shock.final.tenants<values.tenants,'Socially unpopular direct measures spill over via the weighted index');assert.equal(shock.peer,D.rules.collective_happiness.peer_feedback*(shock.directIndex-plain.directIndex),'One finite feedback pass, without recursive amplification');
const base=run('outcome(1,[])'),baseIndex=run('100-aggregate(outcome(1,[]))');ctx.pension=pension;run('fiscalEvents=[{turn:1,levels:{[pension.id]:fiscalSpec(pension).base*.8}}]');const reduced=run('outcome(1,[])'),reducedIndex=run('100-aggregate(outcome(1,[]))');assert.ok(baseIndex-reducedIndex>10,'Twenty-percent pension cut produces a double-digit collective drop including economic and cash incidence');assert.ok(reduced[5]>base[5]+10,'Owners feel the pension cut and shared climate');run('fiscalEvents=[]');
run("openPolicy(D.measures.findIndex(m=>m.id==='a3_rent_aid_target'));renderPolicyMarket()");const card=node('policy-macro-preview').innerHTML;assert.ok(card.includes('data-indicator="collective_happiness"')&&card.includes('Primer trimestre:')&&card.includes('puntos con esta decisión'),'Every policy includes final and immediate collective preview');
run("openPolicy(D.measures.findIndex(m=>m.id==='a3_buy_existing'));draft.intensity=1;draft.units=100000;draft.shares={a3_cut_pensions:100};readFunding();renderPolicyMarket()");assert.deepEqual(Array.from(run('validateDraft()')),[],'Pension-financed acquisition is a feasible decision');const firstNet=run('(()=>{const a={...draft,start:1},v=outcome(1,[a]);return 100-aggregate(v)})()');assert.ok(firstNet<baseIndex-10,'Financed policy includes strong immediate pension backlash');assert.ok(node('policy-macro-preview').innerHTML.includes('Primer trimestre: '+new Intl.NumberFormat('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1}).format(firstNet)),'Preview displays the actual financed first-quarter index');
const bad=M.clone(pack);bad.model.groups.find(g=>g.id==='foreign_buyers').weight=1;assert.ok(M.validate(bad).length,'Excluded group must remain zero');const sens=M.clone(pack);sens.model.groups[0].collective_sensitivity=1.1;assert.ok(M.validate(sens).length,'Sensitivity bounded and editable');assert.deepEqual(M.fromCatalog(D),pack,'All settings survive import/export');
console.log('PASS: national-group weighting, exclusion, severe vs small cuts, signed taxes, GDP, one-pass spillover, editable sensitivity, financed preview and roundtrip. Pension cut 20%: collective '+baseIndex.toFixed(2)+' -> '+reducedIndex.toFixed(2)+'.');
